### ISSUE TITLE
Tests Failing With SwipeCellKit 2.0

### ISSUE THREAD

**Issue by fishcharlie** [SwipeCellKit/SwipeCellKit#101]
I'm getting the following error when trying to run fastlane scan. It started failing after upgrading to SwipeCellKit 2.0.

```
▸ Building Pods/SwipeCellKit [Testing]
▸ Check Dependencies

❌  /Users/____/____/Code/Pods/SwipeCellKit/Source/SwipeActionButton.swift:39:81: type 'UIFont' has no member 'Weight'

titleLabel?.font = action.font ?? UIFont.systemFont(ofSize: 15, weight: UIFont.Weight.medium)
                    ^



❌  /Users/____/____/Code/Pods/SwipeCellKit/Source/SwipeActionButton.swift:74:48: type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'

attributes: [NSAttributedStringKey.font: font],
             ^

```

**Comment by kurabi** [comment]
2.0 requires Swift 4. What version of@swift are you running?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ricolim** [comment]
I also have the same issue. I am running Swift3 in XCode 9.

**Comment by fishcharlie** [comment]
@ricolim You need to update to Swift 4 as @kurabi said.

**Comment by virajphadte84** [comment]
I  am also getting same issue , even I tried pod deintegrateand then added pods again along with that changed swift language version to swift 4.1 . But still the error is coming.
