### ISSUE TITLE
How do I use it with TWTRTweetTableViewCell?

### ISSUE THREAD

**Issue by annjawn** [SwipeCellKit/SwipeCellKit#103]
I am using TwitterKit and want to be able to use this cool library with the custom twitter feed. TwiiterKit comes with `TWTRTweetTableViewCell` to load tweets into tableview cells and since SwipeCellKit also needs the TableView cell to inherit from `SwipeTableViewCell` how does one go about implementing both for the same TableViewCell?

**Comment by kurabi** [comment]
Create a intermediate subclass that inherits from either of those classes.

**Comment by annjawn** [comment]
But I want to use both in my TableViewCells and swift doesn't allow multiple inheritence so I can't possibly subclass both together.

**Comment by kurabi** [comment]
Subclass twice.

**Comment by annjawn** [comment]
Not sure how I subclass it twice since both are subclasses of UITableViewCell and subclass twice would mean multiple inheritance which doesn't work in Swift.
