### ISSUE TITLE
Can't call closure 

### ISSUE THREAD

**Issue by teplonogov** [SwipeCellKit/SwipeCellKit#104]
Hi! I have a problem: I don't know why, but actions, which i created, appears, but not working. I tap on the buttons, but nothing happens. There are no prints in the console. There is my code. Thanks for helping!

        func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
        
        guard orientation == .right else { return nil }
        
        let deleteAction = SwipeAction(style: .destructive, title: "blabla") { action, indexPath in
            print("delete????")
          
        }
        
        let moreAction = SwipeAction(style: .default, title: "More") { action, indexPath in
            print("More")
        }
        
        //deleteAction.image = UIImage(named: "delete")
        
        return [deleteAction, moreAction]
        
    }

**Comment by kurabi** [comment]
Did you look at sample app and see what the difference is?

**Comment by teplonogov** [comment]
Yep, and I didn't find :(
