### ISSUE TITLE
SwipeTableViewCell inside nested UITableView only shows options on second swipe

### ISSUE THREAD

**Issue by hrushka** [SwipeCellKit/SwipeCellKit#105]
Having a very strange problem. The cell that inherits from SwipeTableViewCell is the only cell in a UITableView thats inside a cell. (this problem does not happen in non-nested cells). 

- The editActionsForRowAt is called correctly to get the actions on swipe
- The cell expands as if to show the two actions (in the correct width), but no actions are shown. 
- Tapping and over-drawing where the actions should appear trigger the correct actions.
- When the cell resets, and swiped again, the actions show correctly.

- editActionsOptionsForRowAt seems to be called correctly
- editActionsForRowAt seems to be called correctly
- Ive tested with titles added and with nil titles, neither images nor titles appear
- Im using local, templated images, a clear background color for the actions and a background color set in the editActionsOptionsForRowAt function.

Thoughts?

**Comment by kurabi** [comment]
What do you mean by a nested cell?

**Comment by hrushka** [comment]
This particular cell is a in a table view that’s nested in another cell.
Here is the structure:

CustomItemCell: UITableViewCell
|_
UITableViewController
|_
CustomItemImageCell: SwipeTableViewCell


The top level cell is being instantiated with a reuse identifier, but the
one that is the CustomItemImageCell is not since it’s always only one cell.

**Comment by kurabi** [comment]
A tableview inside a cell? Please don’t do that. That’s not supported.

**Comment by hrushka** [comment]
Haha well we kind of have to. It’s pretty common around here. Just wanted
to see if you had any ideas on to why the behavior might be happening. If
not no worries. I’ll do a pull request if I find the culprit.
