### ISSUE TITLE
Problem with editActionsOptionsForRow

### ISSUE THREAD

**Issue by teplonogov** [SwipeCellKit/SwipeCellKit#106]
Hello! I've installed SwipeCellKit via cocoapods. So I implemented method editActionsForRow and it worked perfectly. But when I decided to implement editActionsOptionsForRow, my app was crashed, when i swiped the cell. This is that I see in log: 

" Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (5) must be equal to the number of rows contained in that section before the update (5), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).".

 Data is stored in CoreData, I use FetchedResultedController for control it. This is my code. Thanks for helping!

func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
        
        if orientation == .right {
            
            let deleteAction = SwipeAction(style: .destructive, title: "Delete") { (action, indexPath) in
                print("DELETEEEEEE!!!!")
                
                self.deleteObjectFromCoreData(for: indexPath)
            }
            
            return [deleteAction]
            
        } else {
            
            let doneAction = SwipeAction(style: .default, title: "Done", handler: { (action, indexPath) in
                
                        let task = self.fetchedResultController?.object(at: indexPath)
                
                        if !(task?.completed)! {
                            let context = self.container?.viewContext
                
                            task?.completed = true
                            task?.inputTime = NSDate(timeIntervalSinceNow: 0) as Date
                
                            do {
                                try context?.save()
                            } catch {
                                print("ERROOOOOR: \(error.localizedDescription)")
                            }
                        }
            })
            
         return [doneAction]
            
        }
        
    }
    
    
    func tableView(_ tableView: UITableView, editActionsOptionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> SwipeTableOptions {
        var options = SwipeTableOptions()
        options.expansionStyle = .destructive
        options.transitionStyle = .border
        return options
    }

**Comment by kurabi** [comment]
Your `self.deleteObjectFromCoreData(for: indexPath)` isn't removing the row immediately (or at all). So the table view is basically saying that  "you said something was deleted, but everything is the same, going to crash"

**Comment by teplonogov** [comment]
Oh.. Could you prompt, how to resolve this situation? I'm just learning. Thanks!

**Comment by kurabi** [comment]
The issue with with your delete method, not SwipeCellKit. When you delete an object, make sure it is really gone from the data source.

**Comment by teplonogov** [comment]
But if I don't implement editActionsOptionsForRow it works perfectly and objects is deleted. I can't understand what's wrong. This is my code for delete objects. Sorry for silly questions. 

    func deleteObjectFromCoreData(for indexPath: IndexPath) {
        let context = (container?.viewContext)!
        context.delete((fetchedResultController?.object(at: indexPath))!)

        do {
            try context.save()
        } catch {
            print("ERROOOOOOOR: \(error.localizedDescription)")
        }
    }

**Comment by columbbus** [comment]
Hi I am struggling with the same problem. I have a simple array (`songData`) that stores the data for my table view. This is my code:
` func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
        // Right swipe
        if orientation == .right {
            // Delete action
            if indexPath.section != 0 {
                let deleteAction = SwipeAction(style: .destructive, title: "Löschen") { action, indexPath in
                    self.songData.remove(at: indexPath.row)
                }
                deleteAction.font = UIFont(name: "AvenirNext-Regular", size: 15.0)
                return [deleteAction]
            }
        }
        return nil
    }
    
    func tableView(_ tableView: UITableView, editActionsOptionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> SwipeTableOptions {
        var options = SwipeTableOptions()
        options.expansionStyle = .destructive
        options.transitionStyle = .border
        return options
    }`

If I comment out or remove the line `options.expansionStyle = .destructive`, everything works as expected. But if not, the app crashes with the same error that you got. Did you found any solution for this problem @teplonogov ?

**Comment by juanjoseluisgarcia** [comment]
I was having the same problem. Then I read from the docs:

> **NOTE**: You must call SwipeAction.fulfill(with style:) at some point while/after your action handler is invoked to trigger deletion. Do not call deleteRows directly.
`let delete = SwipeAction(style: .destructive, title: nil) { action, indexPath in
    // Update model
    self.emails.remove(at: indexPath.row)
    action.fulfill(with: .delete)
}`

I did that and worked

**Comment by yashjain27** [comment]
you are supposed to comment out tableView.reloadData() in the tableView(editActionsForRowAt) Function

**Comment by sashakid** [comment]
> Data is stored in CoreData, I use FetchedResultedController for control it.

As I understood, the problem in original question is that deletion of rows in table is managed by `NSFetchedResultsController` and crash happened because `SwipeCellKit` also calls `tableView.deleteRows...`. So, I think it's incompatible with `NSFetchedResultsController`.
