### ISSUE TITLE
Customize behaviour of swipe action

### ISSUE THREAD

**Issue by CeceXX** [SwipeCellKit/SwipeCellKit#108]
*customize look

I want to customize the look of an action (aka accessing the layer to change shadow color, offset, etc.). I don't see there's a way to access the layer of a SwipeAction. How can I do it?

**Comment by kurabi** [comment]
Have you tried the `Transition Delegate` as stated int he documentation and getting access to the underlying button to customize?

**Comment by CeceXX** [comment]
I'll try this in a second, thank you.

**Comment by CeceXX** [comment]
Hey, this does not seem to be adding any code. Any hints?

extension SubscriptionsController: SwipeActionTransitioning {
    func didTransition(with context: SwipeActionTransitioningContext) {
        // Add shadow to delete button
        context.button.layer.masksToBounds =  false
        context.button.layer.shadowOpacity = 0.43
        context.button.layer.shadowColor = UIColor(red: 246/255, green: 40/255, blue: 83/255, alpha: 1).cgColor
        context.button.layer.shadowRadius = 4 // blur
        context.button.layer.shadowOffset = CGSize(width: 0, height: 2) // Spread
    }
}

**Comment by CeceXX** [comment]
@kurabi Hi, can we reopen this, please?

**Comment by Valerun666** [comment]
Is it possible to set offset for swipe action? For example I have a collection view cell with corner radius and need the action background to have an offset and cover empty space under the cell.
