### ISSUE TITLE
Customize button inset and spacing

### ISSUE THREAD

**Issue by emuye** [SwipeCellKit/SwipeCellKit#109]
I can't figure out a combination of buttonPadding, maximumButtonWidth and minimumButtonWidth that will let me accomplish something like this when the buttons are fully visible. In this case the button image is 48 pixels wide and there is no title. Is this possible?

[20 pixels] [Button] [16 pixels] [Button] [16 pixels] [Button] [20 pixels]

**Comment by kurabi** [comment]
Please read the ‘Transition Delegate’ portion of the README. This gives you access to the underlying button that you can tweak the content inset in.

**Comment by emuye** [comment]
How would I modify the position of the button and its spacing relative to its parent in the transition? Are there any examples of explicitly setting the spacing between buttons this way?

**Comment by kurabi** [comment]
Did you try setting the `contentEdgeInsets` for the `UIButton`? Meaning, the for the leading and trailing buttons, u can set their left and right content inset to 4 to achieve your desired spacing effect. This may or may not work, depends on what the button looks like.
