### ISSUE TITLE
Allow control on actions container view please

### ISSUE THREAD

**Issue by alexbuga** [SwipeCellKit/SwipeCellKit#11]
My row view has a bottom margin and there's a discrepancy between the actions and the row.
I'll attach 2 screenshots: my custom implementation with a scrollview inside the row, and how it looks with SwipeCellKit.

![screenshot 2017-02-27 11 16 44](https://cloud.githubusercontent.com/assets/2833805/23355426/49b37114-fcde-11e6-931f-f45c9f2fb9db.png)
![screenshot 2017-02-27 11 18 12](https://cloud.githubusercontent.com/assets/2833805/23355460/7166774c-fcde-11e6-8af3-40e3253e1568.png)

**Comment by alexbuga** [comment]
I think I'll need to tinker with `var actionsView: SwipeActionsView?` from the `SwipeTableViewCell`

**Comment by mohsinalimat** [comment]
Hello,

SwipeActionsView.swift file

implement like below lines...

 func addButtons(for actions: [SwipeAction], withMaximum size: CGSize) {
        subviews.forEach { $0.removeFromSuperview() }
        
        for action in actions {
            let actionButton = SwipeActionButton(frame: CGRect(origin: CGPoint(x: 0, y: size.height/2-30), size: CGSize(width: size.width * 2, height: 60)), action: action)
            addSubview(actionButton)
            
            actionButton.addTarget(self, action: #selector(actionTapped(button:)), for: .touchUpInside)
            
            minimumButtonWidth = max(minimumButtonWidth, actionButton.preferredWidth)
            
            switch self.orientation {
            case .left:
                let maskPAth1 = UIBezierPath(roundedRect: actionButton.bounds,
                                             byRoundingCorners: [.topRight , .bottomRight],
                                             cornerRadii:CGSize(width: 30, height:  30))
                let maskLayer1 = CAShapeLayer()
                maskLayer1.frame = actionButton.bounds
                maskLayer1.path = maskPAth1.cgPath
                actionButton.layer.mask = maskLayer1
            case .right:
                let maskPAth1 = UIBezierPath(roundedRect: actionButton.bounds,
                                             byRoundingCorners: [.topLeft , .bottomLeft],
                                             cornerRadii:CGSize(width: 30, height:  30))
                let maskLayer1 = CAShapeLayer()
                maskLayer1.frame = actionButton.bounds
                maskLayer1.path = maskPAth1.cgPath
                actionButton.layer.mask = maskLayer1
            }
        }
    }

**Comment by alexbuga** [comment]
Well I wanted a clean way of accessing the view from my controller, not to tinker with SwipeCellKit code. 
That's what I did eventually. Modified the actionView 'cuz that's what I needed.

**Comment by jerkoch** [comment]
Hey @alexbuga - Good to hear you managed to get it working.  Any chance you can share a sample project? 

I've haven't had a chance think about the best way of accommodating this... maybe it's as simple as exposing the `SwipeActionsView`.  Since the `actionView` extends outside of the cell bounds, I'm not clear how you got the rounded corners all around.

**Comment by alexbuga** [comment]
I got the round corners by clipping the view and setting the corner radius
on the layer.
I can't get the height to shrink though. I will try at home.

**Comment by kurabi** [comment]
This work is not in scope for now but I will welcome pull requests to support something like this.

**Comment by LazyScream** [comment]
@alexbuga 
I want to talk to you about how to do this round in this ActionButton plz !
