### ISSUE TITLE
How to prove SwipeTableOption for each SwipeAction on one orientation?

### ISSUE THREAD

**Issue by tangticco** [SwipeCellKit/SwipeCellKit#113]
I have two SwipeActions when swipe left. However it seems that the SwipeTableOption only apply to the first SwipeAction on that orientation. How to customize each SwipeAction on that orientation? 

Also, it is possible to hide one SwipeAction and when Swipe over a threshold, it will replace the previous SwipeOption?

**Comment by kurabi** [comment]
1. Can you please restate your first question. I don't quiet understand your issue.
2. There is an example of that in the sample app. Please try it there.

**Comment by tangticco** [comment]
Thanks I will try that example!

What I mean is the SwipeTableOption returns an SwipeOption for both direction. However, I have 2 SwipeAction on the right orientation but the swipe option seems to only apply on the first. Can I apply different swipe option to each swipe action on right orientation

**Comment by kurabi** [comment]
How would that work?
