### ISSUE TITLE
Selection Expansion Animation Flicker

### ISSUE THREAD

**Issue by adornoventura** [SwipeCellKit/SwipeCellKit#114]
I am experiencing a strange issue when using the selection expansion style and reveal transition. I am trying to achieve the same thing as the mail app read/unread functionality that is featured in the example app and am using the same code. However, when I implement it in my application and call my method to favorite/unfavorite the swiped cell (the method performs a database write to Firebase) there is a flicker in the bounce back animation.

Normal functionality without calling database method:

![giphy](https://user-images.githubusercontent.com/17580537/32644614-b5d716fc-c5b0-11e7-98d8-83c22a86be0b.gif)

Bounce flicker when database write method is called (nothing else changed in the actual SwipeCell-related code)

![giphy-2](https://user-images.githubusercontent.com/17580537/32644635-d0e6729e-c5b0-11e7-8f25-a8271d7ffb15.gif)

**Comment by kurabi** [comment]
Seems like when the DB is updated the table view is being reloaded and hence it refreshes the view, killing the animation.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by adornoventura** [comment]
Can't believe I didn't realize that, I'm using a Firebase query binded to the tableview so it is reloading the tableview.
