### ISSUE TITLE
Button Horizontal Alignment

### ISSUE THREAD

**Issue by mazkewich** [SwipeCellKit/SwipeCellKit#115]
Please add buttonHorizontalAlignment to SwipeTableOptions. Because for multiline string, it will be always center.

**Comment by kurabi** [comment]
You want the set the text alignment on the button? Or the image?

**Comment by mazkewich** [comment]
@kurabi 
Yes, I want to set text alignment. I've found the place code where you're setting it:
titleLabel?.textAlignment = .center  inside SwipeActionButton class. Current implementation looks like this 
<img width="103" alt="screen shot 2017-11-11 at 8 51 36 am" src="https://user-images.githubusercontent.com/6255159/32686792-b66e595a-c6bd-11e7-8c70-a2e2c208d720.png">

**Comment by kurabi** [comment]
You can have access to the underlying button via the `Transition Delegate` outlined in the readme.
