### ISSUE TITLE
Switch swiping on or off

### ISSUE THREAD

**Issue by mazkewich** [SwipeCellKit/SwipeCellKit#116]
Is it possible to turn swiping action on or off state?

**Comment by kurabi** [comment]
Not sure what you mean. Like enable/disable swiping?

**Comment by mazkewich** [comment]
@kurabi yes, currently I'm using the implementation in my method 'cellForRowAt' like this:
`cell.gestureRecognizers?.forEach { $0.isEnabled = false }`, but I'm not sure that this is a good solution

**Comment by kurabi** [comment]
Just return nil for the SwipeActions in the delegate call back.
