### ISSUE TITLE
Hiding Swipe method completion doesn't call

### ISSUE THREAD

**Issue by mazkewich** [SwipeCellKit/SwipeCellKit#117]
`public func hideSwipe(animated: Bool, completion: ((Bool) -> Void)? = nil)` inside SwipeTableViewCell class. Inside closure `animate(toOffset: targetCenter) {` completion always nil.

After some debugging, I can assume how you can fix it. Inside `perform(action: SwipeAction, hide: Bool) {` (`extension SwipeTableViewCell: SwipeActionsViewDelegate`) you should call `hideSwipe(animated: true)` with handler from action.

**Comment by kurabi** [comment]
I tested this and it works fine. Please make sure the animated parameter is true.
