### ISSUE TITLE
Customization question

### ISSUE THREAD

**Issue by sosedoff** [SwipeCellKit/SwipeCellKit#118]
Hi there, im trying to figure out if SwipeCellKit can be customized to look something like 
in the gif below. In the example gif the cell actions have a custom style (rounded corners) and the padding inset to match the cell's style. 

![slider](https://user-images.githubusercontent.com/71051/32762140-349223a6-c8bd-11e7-8e68-52d407066983.gif)

Is something like that supported?

**Comment by kurabi** [comment]
Without forking, no. Easily done with a fork. Customizing and having access to the UIButton is something I would like to improve in the library.
