### ISSUE TITLE
iPhone X landscape issue

### ISSUE THREAD

**Issue by beimen** [SwipeCellKit/SwipeCellKit#119]
I download the demo and run in an iPhone X simulator.

There's a issue about iPhone X simulator in landscape:

![image](https://user-images.githubusercontent.com/1940699/32823837-2fb20c7e-c9a4-11e7-9832-9bb45dde2033.png)

**Comment by MMOmaster35** [comment]
I have the same problem. When could this be fixed?

**Comment by Appsido** [comment]
+1

**Comment by kurabi** [comment]
@joebenton This issue is now fixed and will be part of next release.
