### ISSUE TITLE
The action is sometimes not shown

### ISSUE THREAD

**Issue by SeRG1k17** [SwipeCellKit/SwipeCellKit#121]
Everything you need can be understood from gif.
![bug](https://user-images.githubusercontent.com/13317173/32983170-c2feaf1e-cca1-11e7-89c7-5fe1f047d01f.gif)

```swift
    func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
        guard orientation == .right else { return nil }

        let deleteAction = SwipeAction(style: .destructive, title: nil) { action, indexPath in
            // handle action by updating model with deletion
        }

        // customize the action appearance
        deleteAction.title = "Delete"
        deleteAction.image = #imageLiteral(resourceName: "trash")

        return [deleteAction]
    }

    func tableView(_ tableView: UITableView, editActionsOptionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> SwipeTableOptions {

        var options = SwipeTableOptions()
        options.expansionStyle = .destructive
        options.transitionStyle = .reveal
        options.backgroundColor = .red
        
        return options
    }
```

This is somehow connected with re-use cell. The cell is loaded from .xib

**Comment by kurabi** [comment]
Are you overriding ‘prepareForReuse()’ method?

**Comment by SeRG1k17** [comment]
@kurabi No. The logic of the table is in a separate file with reference to the table object.
```swift
displayManager = NotificationsDataDisplayManager(with: tableView)
```

**Comment by kurabi** [comment]
I am referring to the ‘prepareForReuse’ method on the prepareForReuse method on UITableViewCell

**Comment by SeRG1k17** [comment]
@kurabi I answered :)

**Comment by kurabi** [comment]
Are you using the latest version of the library? This issue was fixed in the last release

**Comment by SeRG1k17** [comment]
@kurabi From Podfile.lock : - SwiftValidator (4.0.0)

**Comment by kurabi** [comment]
There is no such version

**Comment by SeRG1k17** [comment]
@kurabi  SwipeCellKit (2.0.0)

**Comment by kurabi** [comment]
Is it possible to share code that replicates this? Its likely clipsToBounds is being turned on by you, and hence it clips the action views.

**Comment by SeRG1k17** [comment]
@kurabi Thanks, the problem was in clipsToBounds. 
I learned a little about the library code. For the implementation of the сornerRadius, it seems, this is impossible at the moment, since you create an actionsView that is 2x of the width of the cell and is located on one of the sides

**Comment by kurabi** [comment]
You can implement what you need with a background image with cap insets

**Comment by SeRG1k17** [comment]
@kurabi Could you explain your last message a little?

**Comment by kurabi** [comment]
http://iosdevelopertips.com/user-interface/ios-5-uiimage-and-resizableimagewithcapinsets.html

**Comment by SeRG1k17** [comment]
![test](https://user-images.githubusercontent.com/13317173/33172137-f2a738a0-d05f-11e7-89b1-546b3ada6c97.gif)

I'll try to explain how you can achieve such a result with minimal changes to the library code:

set all backgrounds to clear

func configureActionsView(with actions: [SwipeAction], for orientation: SwipeActionsOrientation) {
//...
```swift
        let view = UIView()
        view.backgroundColor = .orangeRed
        view.layer.cornerRadius = layer.cornerRadius
        view.translatesAutoresizingMaskIntoConstraints = false
        insertSubview(view, belowSubview: contentView)
        
        let insets = getSwipeInsets()
        view.topAnchor.constraint(equalTo: topAnchor, constant: insets.top).isActive = true
        view.leftAnchor.constraint(equalTo: leftAnchor, constant: insets.left).isActive = true
        view.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -insets.bottom).isActive = true
        
        let right = NSLayoutConstraint(item: view, attribute: .right, relatedBy: .equal, toItem: self, attribute: .right, multiplier: 1.0, constant: -insets.right)
        addConstraint(right)
        rightConstraint = right
        
        resizingView = view
```
}

and set resizingView lifyCycle logic as actionsView.

after
@objc func handlePan(gesture: UIPanGestureRecognizer) {
//...
// in changed case
rightConstraint?.constant = fabs(target.frame.origin.x) - insets.right

and 
// case ended:
in function animate(duration:toOffset:withInitialVelocity:completion:)
//...
        let distance = offset - center.x
        animator.addAnimations({
            self.center = CGPoint(x: offset, y: self.center.y)
            self.rightConstraint?.constant -= distance
            self.layoutIfNeeded()
)}
//...

**Comment by genefever** [comment]
@SeRG1k17 Hi, I'm trying to change the background cell shape to conform to my custom rounded cell like you showed in the comment above. I'm having difficulties trying to implement it, however. Do you have any projects you wrote with this that I can see?
