### ISSUE TITLE
native "moveRowAt" with SwipeCellKit delete

### ISSUE THREAD

**Issue by Y2JChamp** [SwipeCellKit/SwipeCellKit#124]
Hello,
i'm implementing a tableview whose cell can be reordered (so i need native moveRowAt method) and deleted with a swipe action like the one in your kit. The issue is that if i enable editing in my tableview i have the move function but not your swipe to delete function, and if i disable editing in my tableview, i have your swipe to delete function but not the native cell move feature.

Is there a chance to get both the features?

Thanks

**Comment by kurabi** [comment]
If you want to prefer a gesture to other, then you should try this:
https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/coordinating_multiple_gesture_recognizers/preferring_one_gesture_over_another
