### ISSUE TITLE
I can't Build my app then use that pod

### ISSUE THREAD

**Issue by Lapat1560700104** [SwipeCellKit/SwipeCellKit#125]
<img width="1320" alt="screen shot 2017-12-04 at 3 01 50 pm" src="https://user-images.githubusercontent.com/28327806/33542091-26c592c4-d904-11e7-8934-b62e2bd67a11.png">

**Comment by kurabi** [comment]
Please upgrade to Swift 4 or use a earlier version of SwipeCellKit
