### ISSUE TITLE
Expandable cells

### ISSUE THREAD

**Issue by jlpzb** [SwipeCellKit/SwipeCellKit#127]
Hi there,

I'm trying to implement SwipeCellKit on a table view with expandable cells. When you first start the app, the cells are collapsed:

![01](https://user-images.githubusercontent.com/34538530/33986270-6273d1bc-e0bd-11e7-9259-6c7f5502113f.jpg)

When you click on one of them, the one clicked expands and the others stay collapsed:

![02](https://user-images.githubusercontent.com/34538530/33986295-768d6a14-e0bd-11e7-992f-82df75c28cc2.jpg)

The problem is that when I use SwipeCellKit, the content of every cell is visible from the beginning, as if they were all clicked on and expanded:

![03](https://user-images.githubusercontent.com/34538530/33986706-b4c38cae-e0be-11e7-92ae-b11dac18f288.jpg)

The image shows the first cell as if it was expanded (the white area with the activity indicator) and the second cell with the swipe cell action. As you can see, the content of the first cell is covering the second cell and beyond, even though the first cell wasn't clicked on.

It there a way of fixing this issue?

Thanks,
JL

**Comment by kurabi** [comment]
Please include a example project.
