### ISSUE TITLE
Full Width drawing after swipe several rows in Tableview 

### ISSUE THREAD

**Issue by manuel21** [SwipeCellKit/SwipeCellKit#132]
![simulator_screen_shot_-_iphone_8_-_2017-12-26_at_13_26_49](https://user-images.githubusercontent.com/7534410/34363340-cf57a1fa-ea40-11e7-9fef-95c3cbcaa677.png)

# GIF
![ezgif-2-8d2a43c6da](https://user-images.githubusercontent.com/7534410/34363525-6f312d4e-ea42-11e7-8605-ae7e1d9eab20.gif)

**Comment by kurabi** [comment]
Fix for this is already in the develop branch. Will be releasing soon.

**Comment by kurabi** [comment]
Fixed as part of v2.0.1 that was just released.
