### ISSUE TITLE
Stable version to work with swift 3, as i have not updated to swift 4

### ISSUE THREAD

**Issue by rvinay032** [SwipeCellKit/SwipeCellKit#134]
![screenshot 2018-01-03_11-09-48](https://user-images.githubusercontent.com/30623154/34510085-ccfc9dfc-f076-11e7-83b9-9da61007a6de.png)

Stable version for swift 3

**Comment by kurabi** [comment]
Not interested in maintaining 2 active branches given that Swift 3 will not longer be supported in next version of Xcode (June?).

Cocoapods can allow you to support multiple swift versions together. So you can try that.

**Comment by Neogene** [comment]
Reported problem is related to using IOS 11 SDK functionalities and not iOS 9+ functionalities so building library with min sdk iOS 9 or 10 fails.
