### ISSUE TITLE
Blurred image

### ISSUE THREAD

**Issue by dmitryzhuk1992** [SwipeCellKit/SwipeCellKit#138]
Good afternoon! The issue #50 seems to be closed, but the image is still not sharp. For example, the same image is used. Can you help me?
<img width="355" alt="2018-01-08 17 52 05" src="https://user-images.githubusercontent.com/32683968/34676222-2b81aab4-f49d-11e7-84d1-218fa10a1e34.png">

**Comment by kurabi** [comment]
Can you check the position of the image and see if there is pixel misalignment? Did you enable pixel misalignment in the simulator to confirm that is the issue?

Thanks

**Comment by kurabi** [comment]
Closing due to no response.
