### ISSUE TITLE
[Question] Callback after swipe animation ends

### ISSUE THREAD

**Issue by rhcpfan** [SwipeCellKit/SwipeCellKit#141]
Hello! 

First of all, thanks for all your hard work, it's awesome and helping me a lot!

I have a question, though: is there any callback that is called after the swipe animation finished?

The use-case is the following: I'd like to play a sound when the user starts swiping. I'm doing this right now in the `func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]?`. I'd like to play another sound when the animation ends. I have managed to do so by setting a `transitionDelegate` to one of the `SwipeAction` instances and checking if the `context.newPercentVisible == 1.0` in the `func didTransition(with context: SwipeActionTransitioningContext)` method.

This kinda feels like a workaround... Is there something I'm missing? Any better ways to accomplish this?

Best regards!

**Comment by kurabi** [comment]
@rhcpfan Your solution works fine. Does putting the sound in the `SwipeAction`'s '`handler` not work for you?
