### ISSUE TITLE
Show empty space first time.

### ISSUE THREAD

**Issue by rajindervirk** [SwipeCellKit/SwipeCellKit#143]
I am using below code:-

```
    func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
        guard orientation == .right else { return nil }
        let archieveAction = SwipeAction(style: .destructive, title: nil) { _, indexPath in
            // handle action by updating model with deletion
        }
        
        // customize the action appearance
        archieveAction.image = UIImage.image(name: "icon_Archieve", bundle: podBundle)
        archieveAction.backgroundColor = .red
        return [archieveAction]
    }
```
I am attaching two screenshots with empty space on swiping and having button in second case after scrolling table.
Please help me out.

Thanks

![simulator screen shot - iphone x - 2018-01-24 at 13 14 45](https://user-images.githubusercontent.com/29508213/35320138-c9ea8e7e-0108-11e8-8a00-f6c26e92a579.png)
![simulator screen shot - iphone x - 2018-01-24 at 13 14 52](https://user-images.githubusercontent.com/29508213/35320139-ca299fb0-0108-11e8-8cc8-39b0281bc3b9.png)

**Comment by kurabi** [comment]
What version of the library are you using? Please update to latest version.

**Comment by rajindervirk** [comment]
No @kurabi .

The issue was that i was using clipsToBounds = true in cell class.

It is fixed now.

**Comment by alexruden** [comment]
almost the same: cell.layer.masksToBounds = true
Thanks, @rajindervirk
