### ISSUE TITLE
Title text misplaced

### ISSUE THREAD

**Issue by ramkanpur123** [SwipeCellKit/SwipeCellKit#144]
The title of the Swipe action is cutting with bottom, and I am not sure where contentVerticalAlignment is or there may be another problem. Please refer ti the attached screenshot and help me. I am new to iOS. Thanks...
![screen shot 2018-01-24 at 4 45 35 pm](https://user-images.githubusercontent.com/32055143/35329478-0d56ec08-0126-11e8-9eb4-357dbdc4528c.png)
.

**Comment by kurabi** [comment]
Please update to latest version of the library. Thanks.
