### ISSUE TITLE
[Question] How to center image and change image size of SwipeAction?

### ISSUE THREAD

**Issue by siralam** [SwipeCellKit/SwipeCellKit#145]
Hello, thanks for your great library!

I have been searching for some time and I really cannot find any doc for centering the image in the Button, or changing the image size of the button.

Is such feature available? Or do we need to generate a whole new image resource with padding respected to the row height (Which I think makes little sense)?

Many thanks!

(Sorry for posting questions in issue, but I think being a reference for late comers are useful.)

**Comment by siralam** [comment]
Figured out the center image part - If you want to center the image, you have to supply `nil` as the title.

**Comment by reena-shinde** [comment]
any solution for changing the image frame?
