### ISSUE TITLE
[Question] Vertically centring the title and image of a `SwipeAction` on tall cells

### ISSUE THREAD

**Issue by halleygen** [SwipeCellKit/SwipeCellKit#149]
When dealing with tall `SwipeTableViewCell`s there is the possibility that the title and image of any `SwipeAction`s are not visible on the screen because they are vertically aligned with the centre of the cell itself.

However, in Mail.app Apple have avoided this problem so that their swipe buttons are vertically aligned with the centre of the visible portion of the cell. This means that when the mail cells are tall and are not entirely visible the "swipe content" is always visible to the user.

Below are some screenshots of this behaviour in Mail.app. You can see that even though the cells are quite tall, the swipe buttons are always visible.
![img_0123](https://user-images.githubusercontent.com/21304129/35565534-0afa10fc-0612-11e8-9850-350c6a6b3f62.PNG)
![img_0124](https://user-images.githubusercontent.com/21304129/35565539-0c90f476-0612-11e8-84e1-bced3beede5d.PNG)

Now compare this to the default behaviour in the example SwipeCellKit app when the cells are tall. You can see that the title and image are not visible due to the cell height.
![simulator screen shot - iphone x - 2018-01-30 at 23 26 04](https://user-images.githubusercontent.com/21304129/35566287-f4b0e854-0614-11e8-8249-b1715e5a25ff.png)

Is it currently possible to have this same Mail.app behaviour using SwipeCellKit?

Thanks!

**Comment by kurabi** [comment]
This is currently not possible. PRs are welcome.
