### ISSUE TITLE
maximumButtonWidth requires minimumButtonWidth set?

### ISSUE THREAD

**Issue by jbuckner** [SwipeCellKit/SwipeCellKit#150]
I'm trying to set `SwipeTableOptions.maximumButtonWidth`, but it doesn't seem to have any effect unless I also set `SwipeTableOptions.minimumButtonWidth`. Is this expected behavior? I'm using 2.0.1, iOS 11.2.

**Comment by kurabi** [comment]
@jbuckner If the maximumButtonWidth is below the default/computed minimumButtonWidth, then the maximumButtonWidth is not considered.

I can see why this is confusing as the API does not state this. I will add better API docs with regards to this.
