### ISSUE TITLE
Swipe cells working intermittently 

### ISSUE THREAD

**Issue by tomsiracusa** [SwipeCellKit/SwipeCellKit#153]
I've added SwipeCellKit to my tableview.    I can always swipe on the cell, but the icons and text are not showing up.   If I swipe a few times they then show up.   I have 3 tableviews and this is happening on 2 of the 3.   They all have the exact same code, so I can't figure out why this is happening.

**Comment by kurabi** [comment]
What version of the SwipeCellKit are you using? This was fixed in latest version.

**Comment by tomsiracusa** [comment]
I'm using 2.0.1.   I executed 'pod outdated' and it say that none of my pods need updating.

**Comment by kurabi** [comment]
Please see #143
