### ISSUE TITLE
Update documentation to use SwipeTableViewCellDelegate in class definition

### ISSUE THREAD

**Issue by jp1987** [SwipeCellKit/SwipeCellKit#155]
Great library, thanks! 

I'm fairly new at Swift/iOS development and I wasted some time on the fact that my ViewController didn't extend/implement ``SwipeTableViewCellDelegate``

So: ``class MyViewController extends: UITableViewController, SwipeTableViewCellDelegate``

Perhaps this should be added to the documentation to make a little more newbie friendly.

**Comment by smittyb42** [comment]
until i read this I had wasted a good bit of time on this issue!

**Comment by kurabi** [comment]
There would be a compilation error if you did this in Swift, or a warning in Objective-C.

**Comment by jp1987** [comment]
There wasn't. Xcode 9.2 and Swift 4. Wouldn't have wasted so much time if there was an error.

**Comment by kurabi** [comment]
Remove the delegate declaration in the sample app. You can see any error occur.
