### ISSUE TITLE
iOS 11 have a bug

### ISSUE THREAD

**Issue by ChaoBoyan** [SwipeCellKit/SwipeCellKit#159]
if swipt left ,the siwpeView is show unnormal... help me.help us

**Comment by ChaoBoyan** [comment]
![Uploading WechatIMG43.jpeg…]()

**Comment by ChaoBoyan** [comment]
![Uploading WechatIMG43.jpg…]()

**Comment by ChaoBoyan** [comment]
I  guess , in swipeactionview.swift , the method ....  init(maxSize: CGSize, options: SwipeTableOptions, orientation: SwipeActionsOrientation, actions: [SwipeAction]) {
there is code: 
                         super.init(frame: .zero) //may have troubel in ios11
                         now,i chage it, by fixed value
}
I just need to show one button,so.....fiexe  value
if you have good idea...can do it perfectly

**Comment by kurabi** [comment]
Please update to latest version of the library.
