### ISSUE TITLE
Add a UISwitch component to SwipeActionsView

### ISSUE THREAD

**Issue by MarcoFilosi** [SwipeCellKit/SwipeCellKit#160]
This is an enhancement request.
It would be nice to have `SwipeAction` more customizable by having possibility to add a UISwitch component to switch on/off a specific feature. For example to switch on/off download of a specific item in the UITableView.

Please see picture below on how it should look like:
 ![Image of SwitchOnSwipeCellKit](https://i.imgur.com/zOOScYq.png)

**Comment by kurabi** [comment]
Please see comments on PR.

**Comment by MarcoFilosi** [comment]
@kurabi, based on your comments on PR I've created a new issue (#162) to add a custom UIView instead of button. Please see description and comments there. Thanks
