### ISSUE TITLE
Making SwipeTableViewCell a protocol ?

### ISSUE THREAD

**Issue by 368433** [SwipeCellKit/SwipeCellKit#164]
Hello all,

I was wondering if it were possible to make the SwipeTableViewCell a protocol (and its implementation go in an extension to the protocol) ?
Here is my scenario: I have a tableViewCell that is already inheriting from a class (call it classA). I cannot make it inherit from SwipeTableViewCell at the same time unfortunately. The functionality of this library are great, and I would love to incorporate them.
So my thinking is that if SwipeTableViewCell is a protocol, I could adopt it in my custom tableViewCell class, while keeping its prior inheritance to classA.

Has that possibility been envisaged?
Thanks,
AI

**Comment by kurabi** [comment]
Not possible because protocol extensions can not override methods. Consider switching your other class to a protocol extension if it works for it.

**Comment by 368433** [comment]
thanks
AI
