### ISSUE TITLE
How to not allow swipe the cell, when the swipe button is selected

### ISSUE THREAD

**Issue by Iamivan1996** [SwipeCellKit/SwipeCellKit#169]
i am going to develop the function, when i click on the swipe button, it will hide automatically and not allow to swipe the cell again.    

if orientation == .right && (testingArray[indexPath.row] == false) {
            let btnTakethis = SwipeAction(style: .default, title: "TAKE THIS") { action, indexPath in
                self.testingArray[indexPath.row] = true
            }
            btnTakethis.hidesWhenSelected = true
            let image : UIImage = UIImage(named: "btn_menu")!
            btnTakethis.font = UIFont.boldSystemFont(ofSize: 12.0)
            btnTakethis.backgroundColor = #colorLiteral(red: 0.996206224, green: 0.781045258, blue: 0.1831639111, alpha: 1)
            return [btnTakethis]
        }

Here is my part of code, it is work perfectly to not allow the cell swipe again if the SwipeState is center. When i click the button, it will close with an animation, but it is still can swipe until the state is center

**Comment by kurabi** [comment]
Its not clear to me what you are trying to do. Please post a sample app or a screenshots of what you are trying to accomplish. Closing this issue for now. Thanks.
