### ISSUE TITLE
Provide a way to adjust positions of icons

### ISSUE THREAD

**Issue by zummenix** [SwipeCellKit/SwipeCellKit#170]
It's really valuable when icons are visually not centered. For more information you can read: https://medium.com/@lukejones/optical-adjustment-b55492a1165c

The proposed implementation should be relatively simple:
- Add `var imageInsets = UIEdgeInsets()` and `var highlightedImageInsets = UIEdgeInsets()` in `SwipeAciton.swift`
https://github.com/SwipeCellKit/SwipeCellKit/blob/6544ff983800051c3b0a4a8638cd62f60bdc5063/Source/SwipeAction.swift#L54-L62

- Use `imageInsets` and `highlightedImageInsets` to adjust the rect of the image in `SwipeActionButton.swift` based on `isHighlighted` property of the button
https://github.com/SwipeCellKit/SwipeCellKit/blob/6544ff983800051c3b0a4a8638cd62f60bdc5063/Source/SwipeActionButton.swift#L84-L88

- Override `isHighlighted` property of `SwipeActionButton` and force the button to call `imageRect`

**Comment by kurabi** [comment]
I agree with the need, and there are 2 ways you can solve this:

1. Provide a image that is already inset that makes it visually centered
2. You can get access to the underlying action `UIButton` via the `transitionDelegate`

While both are not the cleanest of solution. I plan on exposing the `UIButton` for needs like yours and others.
