### ISSUE TITLE
UIPageViewController scroll blocked

### ISSUE THREAD

**Issue by jbouaziz** [SwipeCellKit/SwipeCellKit#172]
I've implemented a `UIPageViewController` with horizontal scrolling between its controllers and the default behaviour is broken with swipe cells.

A bit more context about those controllers:
- Controller 1 has `SwipeTableViewCell` subclasses.
- Controller 2 is a regular `UIViewController`
- Controller 3 is a regular `UIViewController`

When panning over those cells to go from `1` to `2`, nothing happens even though there are no actions available on the right side of the cells. There are some on the left side.

Any idea on how to fix that? Am I missing a swipe option or else?

**Comment by kurabi** [comment]
You have competing pan gestures. Just because you have no actions on the right, it doesn't mean the right pan gesture is available for usage. There are other things that that may happen when swiping right, like closing the swiped cell, elastic over pan, cancelling pan gesture, etc.

You can look at this open PR to see if it helps:
https://github.com/SwipeCellKit/SwipeCellKit/pull/163

**Comment by jbouaziz** [comment]
Do you have any idea on how to make a working version of what I’m trying to achieve? I could make a PR myself.
In #163 there is a mention of SwipeCell not cancelling the gesture if not recognized.

**Comment by jbouaziz** [comment]
Why would there be a recognized pan gesture when swiping right to left on a cell that doesn’t have right actions nor is in any pending state (closing a swiped cell, elastic pan gesture, etc.) ?

**Comment by kurabi** [comment]
A pan gesture is not exclusive to a direction. So as I pan on a cell to the right, I can pan left to close it. The UX you are trying to achieve is also not ideal, on a different view control swiping right switches page control but swiping right on another triggers a swipe? Not consistent behavior for the user.

**Comment by jbouaziz** [comment]
What I meant is that there are never right actions on controller 1. That makes the page view controller swipe between its child’s a consistent UX behavior, currently broken by swipe cells.

Jonathan Bouaziz
________________________________

**Comment by raja-velu** [comment]
I also having same issue which is @jbouaziz faced.

**Comment by raja-velu** [comment]
I am using page view controller with 4 child controllers. All 4 controllers are implementing swipecellkit.

**Comment by raja-velu** [comment]
@jbouaziz  I found this workaround :)

 var swipeEnabled:Bool = true {
        didSet {
            panGestureRecognizer.isEnabled = swipeEnabled
        }
    }
put this code in your subclass. Set false if you want to disable pan gesture. It is working well in my case.

**Comment by jbouaziz** [comment]
@raja-velu your solution only works if you know that the gesture needs to be disabled. In my case I need to rely on the cell to know that the gesture failed and let got of the user pan event.
So unfortunately it wouldn't work for me, but thanks!
