### ISSUE TITLE
SwipeAction Buttons' Accessibility Identifiers

### ISSUE THREAD

**Issue by madiguzel** [SwipeCellKit/SwipeCellKit#173]
Hi there,

Big thanks for this awesome library. I wonder how I can set accessibility identifiers for swipe action buttons. 

Thanks.

**Comment by kurabi** [comment]
@madiguzel Thanks. We take care of all of that for you by default by taking the action title and use that as the accessibility label for that action. If you use just an image for the action, we use the accessibility label on the image you provide.

**Comment by DKalachniuk** [comment]
@kurabi and how can I press my action? 

app.tables.cells.buttons["send-circle"].tap()
like this?
Thank you
