### ISSUE TITLE
Can Swipe Cell Action work with Cell continually updated

### ISSUE THREAD

**Issue by strawherotk** [SwipeCellKit/SwipeCellKit#174]
Hello,

I have a cell which is continually updated (the status for downloading process):
<img width="326" alt="screen shot 2018-03-26 at 09 34 06" src="https://user-images.githubusercontent.com/19721878/37884160-e8c1a1d4-30d8-11e8-8293-5df57f6b6b04.png">

Since I have a _progress view_ to indicate the download process, I need to **refresh continually** the table (about 1 time a second). It seems that I cannot use Swipe Cell in this case, can I?
I tried to implement the Swipe Cell, it does not work. When I swipe, nothing happened. When I debug, in below code, the '**selectedIndexPaths**' get **nil** value.

```
        super.setHighlighted(false, animated: false)
        let selectedIndexPaths = tableView.indexPathsForSelectedRows
        selectedIndexPaths?.forEach { tableView.deselectRow(at: $0, animated: false) }
        configureActionsView(with: actions, for: orientation) 

        return true
    }
```
(SwipeTableViewCell.swift - code line 218)
However, when I stop the download (eg. the view is static, not updated continually), Swipe Cell work normally.

It seems that Swipe Cell can work for static cell only. Is it correct?
If you know somehow to make it work with changing table cell. Please let me know!

Thanks a lot,
Victor.

p/s: Updated:
Actually, sometimes the framework works between the 2 UI refresh event. But it soon gets disappear when the next UI refresh come.
It seems that I need to do some change in my code, not with the framework.

Thanks.

**Comment by kurabi** [comment]
@strawherotk Make sure to call the `super` of any method you override. The bug you describe is related to the `clipsToBounds` flag not being set to `false`, which is usually because of not calling super of some of the methods the `SwipeTableViewCell` overrides.
