### ISSUE TITLE
NavigationController interactivePopGestureRecognizer does not work ?

### ISSUE THREAD

**Issue by CivelXu** [SwipeCellKit/SwipeCellKit#175]
How to Fix it ?

I try to use this
```
 if let reg = self.navigationController?.interactivePopGestureRecognizer {
            tableView.panGestureRecognizer.require(toFail: reg)
        }
```
It does not work ?
Can you help me ?

**Comment by kurabi** [comment]
I added another navigation controller on the example Mail app and it works. Are you customizing the back button in your app?

**Comment by CivelXu** [comment]
yes, I mean the cell swipe gesture may be conflict with navigationController interactivePopGestureRecognizer. the interactivePopGestureRecognizer can work in tableView another dispaly area (such as tableview footer or header).

**Comment by kurabi** [comment]
In the example Mail App, it does not conflict. So make this could be something else.
