### ISSUE TITLE
hideSwipeCell error in Swift 4?

### ISSUE THREAD

**Issue by seenoevo** [SwipeCellKit/SwipeCellKit#178]
I just updated to the latest Xcode 9.3 (9E145), and what worked before the update is giving me a compile error stating:

> 'hideSwipeCell' is inaccessible due to 'internal' protection level

I don't want to mess around with the default library code if I don't have to.

Can this issue be fixed and pushed please?

Thanks.

**Comment by kurabi** [comment]
I don't see this issue in the Sample Mail App. Are you calling `hideSwipeCell()` in your code?

**Comment by seenoevo** [comment]
@kurabi 

I was calling this in my code to hide the expanded swipe on certain actions in previous Xcode version, but causing an issue with the latest Xcode.

Is there a reason why this method should not be made public as I find it useful to call in my app?

**Comment by kurabi** [comment]
You should be using ‘cell.hideSwipe(animated: true)’

**Comment by seenoevo** [comment]
I am calling `cell.hideSwipe(animated: true)`, but I'm also using `myTableView.hideSwipeCell` in my code.

Is this a problem?

**Comment by seenoevo** [comment]
let me get back to you regarding why I used this because there was a particular reason, but I can't run the app currently due to other errors from existing libraries with the updated Xcode, and am currently trying to resolve those other issues

**Comment by seenoevo** [comment]
@kurabi 

Managed to use a non-CocoaPods version (i.e. manual drag-n-drop of library code into my project) and here's the reason why I'm using `myTableView.hideSwipeCell`.

When I swipe left to edit a cell, if I cancel and dismiss the secondary VC, I don't want **that** cell to remain in the "swiped" mode, so I call `myTableView.hideSwipeCell` like so:

```
        let editAction = SwipeAction(style: .default,
                                     title: "Edit") { action, indexPath in
            tableView.hideSwipeCell()
        }
```

However my dummy head just realized the answer to this solution was what you mentioned earlier:
```
        let editAction = SwipeAction(style: .default,
                                     title: "Edit") { action, indexPath in

        let cell: SwipeTableViewCell = tableView.cellForRow(at: indexPath) as! SwipeTableViewCell
        cell.hideSwipe(animated: true)
        }
```
That does exactly the same thing without exposing what was not intended to be exposed, and I assume is the appropriate and correct way to achieve what I want? 🎉🍾

**Comment by kurabi** [comment]
Yep.
