### ISSUE TITLE
UIFont.Weight.medium and NSAttrivutedString.font are only iOS 11.0+ but library is declared iOS 9+.

### ISSUE THREAD

**Issue by Neogene** [SwipeCellKit/SwipeCellKit#179]
Hi, library is declared iOS9+ but UIFont.Weight.medium (line 39 of SwipeActionButton.swift) is an iOS 11.0+

titleLabel?.font = action.font ?? UIFont.systemFont(ofSize: 15, weight: UIFont.Weight.medium)

Same is for line 74 of SwipeActionButton.swift regarding NSAttributedStringKey.font

 return title.boundingRect(with: size,
                                  options: [.usesLineFragmentOrigin],
                                  attributes: [NSAttributedStringKey.font: font],
                                  context: nil).integral

**Comment by kurabi** [comment]
```
@available(iOS 8.2, *)
public static let medium: UIFont.Weight
```

```
@available(iOS 6.0, *)
public static let font: NSAttributedStringKey // UIFont, default Helvetica(Neue) 12
```

No warnings/compile errors in Xcode.

Sample app Works on iOS 9.x simulator.

**Comment by Neogene** [comment]
![schermata 2018-04-06 alle 00 27 04](https://user-images.githubusercontent.com/2322707/38395060-55f3a774-3931-11e8-8fc0-6a1f2297441f.png)
@kurabi

**Comment by Neogene** [comment]
Ok for anyone interested:

If you have already added the library to Podfile:

1) if you don't convert your project to swift 4 you have to fix these lines to the old version (pre swift 4) because project fails to compile,

2) if you do step 1 you can convert the project to swift 4, and then restore the lines to the original instructions and it will compile now without problem.

otherwise

1) remove library from Podfile (save and close workspace)
2) pod update
3) reopen workspace
4) update project to swift 4 
5) close workspace
4) restore library in Podfile
5) pod update
6) reopen workspace
7) build and have fun

**Comment by kurabi** [comment]
The latest version already supports Swift 4. Just do `pod update SwipeCellKit`
