### ISSUE TITLE
Buttons don't appear in cell with custom cornerRadius

### ISSUE THREAD

**Issue by wilson100** [SwipeCellKit/SwipeCellKit#180]
In cell's awakeFromNib method i modify its corner radius:
`layer.cornerRadius = 10`
`clipsToBounds = true`
After that the buttons could be seen only after second or n-th swipe:
https://screencast.com/t/dqH8V4TFFBL

Without those two lines of code it works properly.

**Comment by kurabi** [comment]
I can't see the video because of Flash.

**Comment by kurabi** [comment]
In any case, `clipsToBound`s should not be set to true, because the swipe actions cannot appear.
I suggest you use UIView as a background and apply the `cornerRadius` to that.
