### ISSUE TITLE
Wrong layout

### ISSUE THREAD

**Issue by iLem0n** [SwipeCellKit/SwipeCellKit#183]
Hello, 

while swipe left or right to show the cell actions the layout of the action itself seems to behave wrong. 
Look at the images below.
It‘s not really reproducable because it’s happens often but the on the next swipe it works normally.  
Here ist my delegate for the cell actions: 

`
extension FoodItemsListTableController: SwipeTableViewCellDelegate {
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 100
    }
    
    func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
        var actions: [SwipeAction] = []
        switch orientation {
        case .left:
            let consumeType = (viewModel?.item(at: indexPath)?.consumed ?? false) ? "Unconsume" : "Consume"
            let consumeAction = SwipeAction(
                style: .default,
                title: consumeType,
                handler: { (_, indexPath) in
                    self.viewModel?.consume(at: indexPath)
                })
            consumeAction.backgroundColor = .blue
            actions.append(consumeAction)
        case .right:
            actions.append(SwipeAction(style: .destructive, title: "Delete", handler: { (action, indexPath) in
                self.viewModel?.delete(at: indexPath)
            }))
        }
        return actions
    }
    
    func tableView(_ tableView: UITableView, editActionsOptionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> SwipeTableOptions {
        var options = SwipeTableOptions()
        switch orientation {
        case .left:
            options.expansionStyle = .destructive(automaticallyDelete: false)
        case .right:
            options.expansionStyle = .destructive(automaticallyDelete: false)
        }
        return options
    }
}`

Wrong Layout:
![1ae3bcce-1382-48df-b77c-250b240f1dad](https://user-images.githubusercontent.com/5202672/38554664-b5f83cf8-3cc3-11e8-9e52-979c857425be.png)
![2dca65e9-64b0-4f2e-8581-9dd4c1140da2](https://user-images.githubusercontent.com/5202672/38554665-b61c93e6-3cc3-11e8-848d-8e6a77b610eb.png)

How it should be (and is sometimes):
![bc564e30-4d41-453f-9b1c-e8ab71021502](https://user-images.githubusercontent.com/5202672/38554666-b640c734-3cc3-11e8-8579-f76565d5fb58.png)
![b7d5e9dd-bf4b-4dce-a300-4081d814c031](https://user-images.githubusercontent.com/5202672/38554667-b663f952-3cc3-11e8-9d91-a996c20f16c1.png)

**Comment by kurabi** [comment]
Make sure when overriding any methods with your custom cell, that your are calling the parent method via `super`.

**Comment by iLem0n** [comment]
The only Method I override in this Cell is prepareFoReuse wich super method i call. 


`import UIKit
import SwipeCellKit
import RxSwift

class FoodItemCell: SwipeTableViewCell {
    
    @IBOutlet var titleLabel: UILabel!
    @IBOutlet var dateLabel: UILabel!
    @IBOutlet var productImageView: UIImageView!
    @IBOutlet var imageActivityIndicator: UIActivityIndicatorView!
    @IBOutlet var titleActivityIndicator: UIActivityIndicatorView!

    private var disposeBag = DisposeBag()
    var item: FoodItem? {
        didSet {
            self.disposeBag = DisposeBag()
            if let item = item {
                if let cachedName = productNameCache.object(forKey: NSString(string: item.productEan)) as String? {
                    self.titleLabel?.text = cachedName
                    imageActivityIndicator.stopAnimating()
                }

                item.productObservable
                    .map({ $0?.name })
                    .filter({ $0 != nil }).map({ $0! })
                    .bind(to: titleLabel.rx.text)
                    .disposed(by: disposeBag)
                
                item.productObservable
                    .map({ $0?.name })
                    .filter({ $0 != nil }).map({ $0! })
                    .bind(to: titleLabel.rx.text)
                    .disposed(by: disposeBag)
                
                item.productObservable
                    .map({ $0?.image ?? #imageLiteral(resourceName: "ProductPlaceholder") })
                    .bind(to: productImageView.rx.image)
                    .disposed(by: disposeBag)
                
                item.productObservable
                    .filter({ $0 != nil }).map({ $0! })
                    .subscribe { _ in
                        self.titleActivityIndicator.stopAnimating()
                        self.imageActivityIndicator.stopAnimating()
                    }
                    .disposed(by: disposeBag)
                
                self.dateLabel?.text = DateFormatter(timeStyle: .none, dateStyle: .medium).string(from: item.bestBeforeDate)
                
                if item.bestBeforeDate.isWithin(days: UserSetting.shared.yellowWarningThresholdDays) {
                    self.setState(.warning)
                }
                if item.bestBeforeDate.isWithin(days: UserSetting.shared.redWarningThresholdDays) {
                    self.setState(.error)
                }
            } else {
                self.titleLabel?.text = nil
                self.dateLabel?.text = nil
                self.backgroundColor = .white
                self.productImageView.image = nil
                imageActivityIndicator.startAnimating()
            }
        }
    }

    override func prepareForReuse() {
        super.prepareForReuse()
        self.item = nil
    }
}`

**Comment by iLem0n** [comment]
Closed without a solution ?

**Comment by kurabi** [comment]
Post an example app with issue and will reopen.

**Comment by iLem0n** [comment]
I've reduced my project to the necessary stuff. Error already exists. 
[https://github.com/iLem0n/SwipeCellKitBugExample](url)


1. cd into project folder
2. run 
`carthage bootstrap --no-use-binaries --platform iOS`
3. build & run 
4. try to swipe the cell actions multiple times 

Error is not always

**Comment by iLem0n** [comment]
There are already the necessary frameworks. 

This is a Carthage error with RxSwift. 
Try remove the version tags within the Carthage file. 

But I will try to reproduce the error without the extra frameworks

**Comment by iLem0n** [comment]
updated the project with all unnecessary frameworks

**Comment by iLem0n** [comment]
any news about this ? you wanted to reopen this issue ?!

**Comment by kurabi** [comment]
Project didn't compile. Got it to work. Cells worked fine and I swiped many times. Your code has too much structure/boilrplate to see what you could have done wrong, please review Mail app sample.
