### ISSUE TITLE
Swipe Cell with detail button does not call swipe action

### ISSUE THREAD

**Issue by 368433** [SwipeCellKit/SwipeCellKit#184]
Hello,

A perhaps somewhat related issue was posted about here: https://github.com/SwipeCellKit/SwipeCellKit/issues/16

However I am facing a different situation:
If I give a cell an accessory type .detailButton, the swipe action does not get called
If I give the cell no accessory type it works fine. If i give it the .detailDisclosure type it works fine too.
It seems that the detailButton mode is causing conflict.
Please let me know if more information is needed

**Comment by kurabi** [comment]
@368433 I just tried this on the Mail Example app, and it works:
https://www.dropbox.com/s/y7f25jub0sw8d87/Screen%20Shot%202018-04-10%20at%209.26.49%20PM.png

**Comment by 368433** [comment]
Yes sorry I was not clear. The swipe gesture works well, but triggering the actual action (touching the resulting button - "Trash" in your example for instance) did not trigger the expected action. Does clicking on trash trigger an action in your example ?
However if I change it to any other accessory types, the action gets triggered as expected.

**Comment by kurabi** [comment]
Yep, I see the issue. Not sure what the solution is.

**Comment by jeeva-sil** [comment]
This issue occurs only in UITableView Example. UICollectionView Example seems working fine.

**Comment by kurabi** [comment]
@jeeva-sil You are referring to issue #205. Which has been resolved.

@368433 This issue has been resolved in iOS 11.4.

**Comment by jeeva-sil** [comment]
Ya i checked. It has been resolved in example app but cocoapod version is not updated i think bcoz issue remains in pod version library.

**Comment by kurabi** [comment]
Make sure you are using latest version.
