### ISSUE TITLE
flatMap is deprecated

### ISSUE THREAD

**Issue by seenoevo** [SwipeCellKit/SwipeCellKit#185]
Please update `Extensions.swift` and `SwipeTableViewCell+Accessibility.swift` to use `compactMap` instead of `flatMap` as it is deprecated:

![untitled](https://user-images.githubusercontent.com/8109158/38604474-5119894c-3d25-11e8-8a4f-d56a287688fc.png)

**Comment by kurabi** [comment]
Fix is in develop branch. New version will be released soon.
