### ISSUE TITLE
Pod not working!

### ISSUE THREAD

**Issue by linhkaestner** [SwipeCellKit/SwipeCellKit#189]
Hi everyone, 
these errors appears everytime I want to build my project with SwipeCellKit:

in SwipeTableViewCell+Accessibility.swift line 50:
`Value of type '[SwipeAction?]' has no member 'compactMap'`

in Extensions.swift line 12:
`Value of type '[UITableViewCell]' has no member 'compactMap'`

The Mail Demo Project is also not working and is showing the same errors. 
Please help, thx!

**Comment by kurabi** [comment]
Please upgrade to latest version of swift or use an older version of the project.
