### ISSUE TITLE
About RoundCorners

### ISSUE THREAD

**Issue by LazyScream** [SwipeCellKit/SwipeCellKit#190]
https://s3-ap-northeast-1.amazonaws.com/crackwatch/Simulator_Screen_Shot_-_iPhone_5s_-_2018-04-24_at_23_01_21.png
Is there a way to Round Rounders in the picture circled?
I wish I could have RoundCorners. Is it possible to change the library now?
I hope to get help here, I really like this library thx all !

**Comment by XRadevFRT** [comment]
I have the same problem...

**Comment by LazyScream** [comment]
plz god help us !

**Comment by kurabi** [comment]
There is no support for this. Definitely something that will be worked on in the future. PRs are welcome.

**Comment by hartjosh** [comment]
This would be a great feature...need the same

**Comment by kurabi** [comment]
Also I suggest you use the circular button style with an image or image+text.
Lastly, you might be able to achieve this by using just an image that has the text, and the image containing the rounded corners.

**Comment by kurabi** [comment]
Closing as #162 is inclusive of this feature request.
