### ISSUE TITLE
Wait Swipe Action being closed to open another

### ISSUE THREAD

**Issue by grifas** [SwipeCellKit/SwipeCellKit#197]
I updated the pod to 2.3.0 but there is something different on swipe action.

In 2.1.0, I can swipe directly a cell even if another cell swipe actions is opened. 
In 2.3.0, I can't do the same thing. I have to wait the cell being closed to open another cell.

**Comment by kurabi** [comment]
That’s the correct behavior. I don’t believe this changed. Also 2.2.0 fixed the issue of swiping two cells simultaneously (2 fingers on screen).

**Comment by kurabi** [comment]
Ok I see the issue. I believe 2.2.0 introduced this issue. Will put in a fix.

**Comment by kurabi** [comment]
2.3.1 is out. Thanks for catching that. Great little detail and this project is all about those details.
