### ISSUE TITLE
TableView gesturerecognizer disabled

### ISSUE THREAD

**Issue by RaiseyDaisie** [SwipeCellKit/SwipeCellKit#199]
Hi, apologies as this appears to be similar to a few other questions but I am still struggling with this. 

I have the following gesture added to the tableview in viewDidLoad() ...

```
 override func viewDidLoad() {
        //some initialisation code
        
        let gesture = UISwipeGestureRecognizer(target: self, action: #selector(dismiss(fromGesture:)))
        tableView.addGestureRecognizer(gesture)
        }
    }

@objc func dismiss(fromGesture gesture: UISwipeGestureRecognizer) {
        navigationController?.popViewController(animated: true)
    }
```

the SwipeTableViewCellDelegate protocols adopted as follows ...

```
func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
         if orientation == .right {
            let deleteAction = SwipeAction(style: .destructive, title: "Delete") { action, indexPath in
                self.dataController.deleteSession(for: self.sessions![indexPath.row])
            }
        
            deleteAction.image = UIImage(named: "delete_20pt")

            return [deleteAction]
        }
         return nil //this probably needs to return something else ??
    }
    
func tableView(_ tableView: UITableView, editActionsOptionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> SwipeTableOptions {
        var options = SwipeTableOptions()
        options.expansionStyle = SwipeExpansionStyle.init(target: .percentage(0.9), additionalTriggers: [.touchThreshold(0.8)], elasticOverscroll: false, completionAnimation: .fill(.automatic(.delete, timing: .with)))
        return options
    }
```

The delete button shows up fine when swiping from right-to-left and delete action is executed properly. However, the tableView gesture is disabled somehow and does not execute. It _does_ execute outside of the cells (e.g. when I have no cells or after the last cell) so I know it works. What am I doing wrong here?

**Comment by kurabi** [comment]
Just because you only have one swipe action on the right, doesn’t mean users won’t swipe left in relation to that action. They may want to swipe left to close it, they may swipe right and left in one motion, etc. That being said, what is happening is that the cells swipe gesture is taking priority over your own. So you can try the answers here: https://stackoverflow.com/questions/4875255/is-there-any-priority-condition-between-gesture-methods-pan-gesture-and-swipe-g?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by RaiseyDaisie** [comment]
thank you! that worked
