### ISSUE TITLE
SwipeAction handler does not work after update

### ISSUE THREAD

**Issue by jakejcheng** [SwipeCellKit/SwipeCellKit#205]
I just updated through cocoapods and SwipeAction does not respond to user "click" anymore. editActionsForRowAt still gets called when user swipes but when user clicks, nothing happens. I didn't change any code since the last update and I could not find the problem! Any help would be appreciated!

**Comment by buffstop** [comment]
+1
`let action = SwipeAction(style: .default, title: "title") { action, indexPath in
                // This is never called.
            }`

**Comment by kurabi** [comment]
Works fine in Mail app example. Can you make sure you do a deep clean of your app and try again?

**Comment by kurabi** [comment]
This is similar to #204 that turned out to be a non issue but I can’t imagine it’s coincidence now. 🤨

**Comment by kurabi** [comment]
OK, I found the issue. This has been resolved in v2.4.1

**Comment by buffstop** [comment]
Confirmed fixed. Thanks!
