### ISSUE TITLE
Cell contentView size issue with iPhone X in landscape

### ISSUE THREAD

**Issue by sparga** [SwipeCellKit/SwipeCellKit#206]
When swiping a cell on an iPhone X in landscape, the cell content size width is changing causing the text in its label to be re-layouted.
It seems to be related to the safe area because the size of the content view changes by the safeAreaMargin value.
I created a gif with the demo project to illustrate this:

![swipecellkit](https://user-images.githubusercontent.com/849905/40816507-446f56ae-6502-11e8-9848-ead349b051de.gif)

You can clearly see the _you_ being moved to the second line. You can also notice that the border animation does not start from the edge of the screen like in the real Mail app.
Do you think this can be fixed easily?

**Comment by kurabi** [comment]
The content view issue doesn’t happen in latest version and it’s only an example app issue from what I can see. Regarding boarder transition, I’ll need to check but is not a high priority on my list. Feel free to submit a PR.

**Comment by sparga** [comment]
I still have the contentView issue in my project and in the example app with v2.4.1. From what I understand, it seems to be only with multiline labels.
I looked at the code but didn't find anything obvious to would fix that as the `contentView` is never changed for the `SwipeTableViewCell`.

**Comment by kurabi** [comment]
Weird. I will take a look.

**Comment by kurabi** [comment]
If you make subject and body labels cell width equal to that of containing UIStackView, the movement issue goes away.  Also this occurs on simulator only from what I can see.

**Comment by sparga** [comment]
Thank you for the support. I'll try to change the constraint then.
