### ISSUE TITLE
Swift 4.2+ support

### ISSUE THREAD

**Issue by Gskflute** [SwipeCellKit/SwipeCellKit#212]
Hello, 

Want to know if there will be swift 4.2+ support?

thx

**Comment by kurabi** [comment]
I don’t believe there is any changes required but then again the beta just came out yesterday.

**Comment by kurabi** [comment]
Please see `swift_4.2` branch. So to access it via Cocoapods, you can do:
```pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'swift_4.2'```

**Comment by kreeger** [comment]
Thanks for this, @kurabi — I wouldn't be surprised if a future Xcode beta fixes this issue by itself, but the changes in the `swift_4.2` are super handy as we move to try and adopt Swift 4.2 as early as possible.
