### ISSUE TITLE
swipe on a new cell

### ISSUE THREAD

**Issue by lvloh3n** [SwipeCellKit/SwipeCellKit#214]
Hi
Thank you for your great framework. There is something that if added can result to a better user experience.

In apple row actions when you do this action: "swipe on a cell and then swipe on another cell" will result in the previous cell hiding it's row actions and the new cell showing them.

But here it will only hide the previous cell row actions and I have to swipe again to see the new cell row actions.

Meaning I have to do 2 swipes.
Is there a way to make it a one step swipe right now?

**Comment by kurabi** [comment]
Make sure you are using latest version. You should be able to swipe a closed cell while another cell is open.

**Comment by kurabi** [comment]
Closing unless I misunderstood your concern.

**Comment by lyc2345** [comment]
Hi, I am using 2.4.3. I swipe a cell to open options then I swipe another cell. The previous cell still show options So Now I have 2 cells options is opening. And I can open more cell without previous' close.

I check example and didn't see any function or way you're close the previous cell.

 I also put breakpoint to every delegate function. But When I swipe another cell, The Previous cell would close first then break on the breakpoint.

Is there I missing some key to close previous opening cell?

Thank you for your reply.

**Comment by kurabi** [comment]
Is this in just 2.4.3 or previous versions also? What is different between your app and example mail app?

**Comment by lyc2345** [comment]
Hi, @kurabi 
Example app if I swipe first then swipe second, the first one will close automatically. But in my app the first keeps showing so if I swipe the third, forth and so on... All swiped cell is showing.

I'm not sure which versions is working correct. But I cloned directly and the SwipeCellKit target version is 2.4.3.

**Comment by kurabi** [comment]
What is different between sample app and your code? Post example project

**Comment by lyc2345** [comment]
@kurabi  I update my comment and include my code, thanks a lot !!!

**Comment by kurabi** [comment]
1. Can you please post a sample app.
2. Is `didMoveToSuperview` getting called on the SwipeCollectionViewCell?
3. Make sure you are calling super on any method you override in `ShowroomCell`

**Comment by lyc2345** [comment]
@kurabi Thanks for your reply.
I move my code to a new example project and it works. And I peel my code and find out all because I had two sections in my collectionView. How could I just enable swipe for only specific section?
