### ISSUE TITLE
left, I return nil, and the left will appear a blank.

### ISSUE THREAD

**Issue by daishuyi** [SwipeCellKit/SwipeCellKit#215]
The first, drag to left, the right actions will appear.
The second, drag to right and the left will appear blank
The third, when I stop drag, it will reset with an animation. But I tap the cell, the animation stop before completion. So that the left remain a blank.

![wechatimg2](https://user-images.githubusercontent.com/38234719/41391488-8df921e4-6fcd-11e8-844d-bc637177c18b.jpeg)

**Comment by kurabi** [comment]
What version of SwipeCellKit are you using?

**Comment by daishuyi** [comment]
Your demo, you should return nil when orientation == .left.

**Comment by daishuyi** [comment]
pod 'SwipeCellKit', '~> 2.2.0', the bug can't reset perfectly ----> only  orientation = .left or .right

**Comment by kurabi** [comment]
Please upgrade to latest version, I don't think is occurs in v2.4.2

**Comment by daishuyi** [comment]
Now, I use 2.4.2，it is the same bug.  Please close left, and use iPhone(my iPhone is 8 Plus), try to use two hands as far as possible, and the bug will appear.
 
 
------------------ Original ------------------
From: "Mohammad Kurabi"; 
Date: 2018年6月14日(星期四) 下午2:37
To: "SwipeCellKit/SwipeCellKit"; 
Cc: "yidai"; "Author"; 
Subject: Re: [SwipeCellKit/SwipeCellKit] left, I return nil, and the left willappear a blank. (#215)

 

Closed #215.

**Comment by daishuyi** [comment]
This is your demo, use 2.4.2 (pod installed)
[SwipeCellKit-2.4.2.zip](https://github.com/SwipeCellKit/SwipeCellKit/files/2101401/SwipeCellKit-2.4.2.zip)

this is bug 
![wechatimg3](https://user-images.githubusercontent.com/38234719/41400033-8c140aa8-6fee-11e8-941d-8c32fc61fa6e.jpeg)

**Comment by daishuyi** [comment]
![1528965196691](https://user-images.githubusercontent.com/38234719/41401663-fe6d2d88-6ff2-11e8-9d12-93bdb198c82f.jpg)

**Comment by kurabi** [comment]
What iOS version are you on? I tried to reproduce this but I can't. I tried on device too iOS 11.

If you are on iOS 11, please do a screen recording in case I am not understanding how you are running into this issue.

**Comment by kurabi** [comment]
Ok I see the issue now. Not easy to reproduce.

**Comment by kurabi** [comment]
Please look at the fix in `develop` branch and let me know if it addresses the issue. Will release this after some testing.

**Comment by daishuyi** [comment]
OK， I use the develop branch version,  .ended, .cancelled, .failed to reset .  It is beautiful, when do you publish the new release version?  

 
 
------------------ Original ------------------
From: "Mohammad Kurabi"; 
Date: 2018年6月15日(星期五) 中午1:34
To: "SwipeCellKit/SwipeCellKit"; 
Cc: "yidai"; "Manual"; 
Subject: Re: [SwipeCellKit/SwipeCellKit] left, I return nil, and the left willappear a blank. (#215)

 

Please look at the fix in develop branch and let me know if it addresses the issue. Will release this after some testing.

**Comment by daishuyi** [comment]
And thanks to support !  I find that you modified a lot of code.

**Comment by kurabi** [comment]
Yep. That’s why it needs a good testing period before release.
