### ISSUE TITLE
Swift version issue

### ISSUE THREAD

**Issue by chiragpurohit71085** [SwipeCellKit/SwipeCellKit#217]
After installing when I opened project, it says SwipeCellKit developed with swift 2.x. I have tried
both branches. My project is in Objective - C

i.e

# Get the latest on develop
pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'develop'

# If you like to live dangerously
pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'swift_4.2'

**Comment by kurabi** [comment]
What is your issue?

**Comment by chiragpurohit71085** [comment]
When I install library usit cocoa pod and started my project, xcode says
swipecellkit is developed in xcode 2.x

**Comment by kurabi** [comment]
This project does not support objective-c.
