### ISSUE TITLE
Ambiguous use of 'frame'

### ISSUE THREAD

**Issue by lukepistrol** [SwipeCellKit/SwipeCellKit#220]
I'm getting this error in every line where .frame is called on the variable swipeable.

For example:
`swipeable.actionsView?.visibleWidth = abs(swipeable.frame.minX)`

**Comment by kurabi** [comment]
I am assuming you are on Xcode Beta. So use that branch.

**Comment by lukepistrol** [comment]
I already noticed the branch. That’s why I closed this thread
