### ISSUE TITLE
reload cell causes selection animation to fail

### ISSUE THREAD

**Issue by AlexanderBollbach** [SwipeCellKit/SwipeCellKit#222]
I'm using this library w/ `RxDataSources` in an MVVM context.  In the `SwipeAction`'s handler I update my view model which ultimately tells the table view data source to reload that cell.  All I do when reloading the cell is set some internal labels.  

Something about reloading the cell causes the selection animation (where the actions slide back out to the right) to not happen.  I'm not sure if this has to do with `RxDataSource` using its own animation when it reloads cell and that interfering with your animations.  

Its difficult to dig into the source for RxDataSources and your library and diagnose the problem (especially as I'm using Carthage and can't directly see the source in Xcode!)  

Do you have any thoughts about this?

**Comment by kurabi** [comment]
That’s because the whole cell is being reloaded, and the animation state is lost. You need to only update the labels that you want instead of reloading the cell. My guess is there should be a way to do that in RxDataSources where you get told that an “update is about to happen to a cell, how do you like to proceed”.

**Comment by AlexanderBollbach** [comment]
@kurabi thanks, i'll look into that.  I think that RxDataSources is predicated on using tableview's API as much as possible.  As a hack (if any one ever also runs into this) I delay the update for as long as the SwipeCellKit animation's duration (or roughly) and that looks more or less fine.

**Comment by kurabi** [comment]
Well there is a animation completion callback so maybe u can do it there.
