### ISSUE TITLE
Swipe actions appear at center of the cell by default

### ISSUE THREAD

**Issue by Mijail** [SwipeCellKit/SwipeCellKit#223]
Hi there. I don't know if it can be customized but I think it should be a default behaviour.

In apple Mail.app when you are in a thread (conversation) and you swipe any of the messages, the swipe actions appear on the visible part of the cell if some part of it is hidden. On the other hand Swipe cell Kit actions appear always on the center of the cell if I recall correctly.

That means that If a cell has a big height value, the actions won't be visible unless you swipe exactly at the center of the cell.

I can post screenshots if I didn't make myself clear.

Thanks

**Comment by kurabi** [comment]
This is already supported. Please read the Advanced.md part of the docs.
