### ISSUE TITLE
Cannot get delete to work with custom cell class for UITableViewCell

### ISSUE THREAD

**Issue by ChrisWi** [SwipeCellKit/SwipeCellKit#225]
I have been trying for days to get this working. The code I am using is here:

https://stackoverflow.com/questions/51184331/deleting-a-custom-view-from-uitableview?noredirect=1#comment89571813_51184331

Is this an issue? I need help and want to use this plugin.

**Comment by kurabi** [comment]
The Mail example app has a delete function. Please look at that.

**Comment by kurabi** [comment]
Make sure you are calling super for any functions you are overriding.
