### ISSUE TITLE
Swipe Cell Sensitivity 

### ISSUE THREAD

**Issue by simonzwicker** [SwipeCellKit/SwipeCellKit#230]
Hey Guys,

my AppCustomers have the problems that they scroll through the list and the Cell will Swipe too easy and stop scrolling the list. Is there a possibility to set a sensitivity or something?

Greets
Simon

**Comment by kurabi** [comment]
What version of SwipeCellKit are you on? Most recent releases are less susceptible to that to that.

**Comment by simonzwicker** [comment]
on version 2.1.0

**Comment by kurabi** [comment]
Please upgrade to latest. Which is 2.4.3.

**Comment by lsmilek1** [comment]
Hello, I am using this pod in a collection view and it still seems to be very sensitive. Very often it swipes instead of scroll.
