### ISSUE TITLE
cell's pan gesture will intercept my custom screen edge pan gesture

### ISSUE THREAD

**Issue by vergilw** [SwipeCellKit/SwipeCellKit#231]
i have a screen edge pan gesture, but not work if a use swipe cell.
how to slove it?

**Comment by bogren** [comment]
I have the same issue. Swipe to interactive pop doesn't work. Works fine in my test project that I created, but doesn't work when I implement `SwipeCellKit` in my project. Currently investigating.

**Comment by bogren** [comment]
Found the issue related to #175. Adding a custom back item breaks the pop, that can be fixed by e.g setting the `interactivePopGestureRecognizer` to `nil`. But that would break the swipe on cells, still work fine in the collection view. Setting the delegate or editing the back button seems to fix it! ✅

**Comment by rjchrhl** [comment]
It would be great if SwipeCellKit's gestures were directly accessible. Until then, here's a solution I've used:

extension SwipeCollectionViewCell {

    // SwipeCellKit adds a pan gesture recognizer to each SwipeCollectionViewCell
    // but doesn't expose it publically; so search for and expose it,
    // allowing callers can use it to set up dependancies between multiple gestures
    //
    // ex: make it dependent on interactivePopGestureRecognizer failing before it triggers (to prevent gesture conflict)

    // usage:
    //
    // caller first sets cell's delegate:                    swipableCell.delegate = self
    // afterwards, call this method to find gesture          let gesture = swipingCellPanGesture()
    // then caller can adjust gesture dependancies           swipeCellGesture.require(toFail: interactivePopGestureRecognizer)

    func swipingCellPanGesture() -> UIPanGestureRecognizer? {
        if let recognizers = gestureRecognizers {
            for recognizer in recognizers {
                if let cellPanGesture = recognizer as? UIPanGestureRecognizer {
                    return cellPanGesture
                }
            }
        }
        assert(false, "SwipeCollectionViewCell UIPanGestureRecognizer not found (was cell's swipe delegate set before calling?)")
        return nil
    }
}

**Comment by kurabi** [comment]
UINavigationController’s edge back gesture works fine with SwipeCelllKit, so how does that work without needing to know about SwipeCellKits pan gesture?

**Comment by bogren** [comment]
As @kurabi said works fine. It's just that the issue appears when using SwipeCellKit. What worked for me is fixing the hack we had for our custom navigation controller or fix the problem with custom back button. 

This code in our custom navigation controller fixed it without editing our custom back button.
```
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
    return YES;
}
 - (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer
{
    return [gestureRecognizer isKindOfClass:UIScreenEdgePanGestureRecognizer.class];
}
```

**Comment by kurabi** [comment]
Anyone want to make a case for this before I close this issue?

**Comment by rjchrhl** [comment]
As I mentioned, it would be great if SwipeCellKit's gestures were directly accessible. Without direct access to it, any code written has to make assumptions/guesses when dealing with gestures.

The "shouldBeRequiredToFailByGestureRecognizer" method referenced above is an example of that, with its usage of "isKindOfClass:UIScreenEdgePanGestureRecognizer.class" which is really just masking that this code is actually exists to deal with SwipeCellKit's gesture.

**Comment by kurabi** [comment]
@rjchrhl I don’t see how @bogren solution would be better off with access to the swipe cells internal gesture recognizers. Also, exposing them leads to a host of other issues and challenges as each cell has its own gestures, so others would need to make sure they are not retaining the cell, needs to ensure and understand that the cells are re-used and do what ever logic they may need to do every time the cell becomes in view.

No one has addressed how the native back edge gesture recognized works without needing to know about the swipe cell, so I would suspect it’s something similar to @bogren’s solution.

**Comment by prabhakar648** [comment]
HI, 
Am using the SwipeCollectionView as Parent to my BaseCollectionViewCell, due to which at certain places in my app the horizontal swipe doesn't work for collectionview. Any idea or solution for this problem.

**Comment by tianzhuqiao** [comment]
Just in case someone still needs this. The [following way](https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/coordinating_multiple_gesture_recognizers/preferring_one_gesture_over_another) works for me, my gesture recognizer will be call first (before the pan gesture in swipecell)
```swift
class MyViewController: UIViewController, UIGestureRecognizerDelegate {
    override func viewDidLoad() {
         ...
        let swipeRight = UIScreenEdgePanGestureRecognizer(target: self, action: #selector(respondToSwipeGesture))
        swipeRight.edges = .left
        swipeRight.delegate = self
        self.view.addGestureRecognizer(swipeRight)
         ...
    }
    
    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer,
                           shouldBeRequiredToFailBy otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        // Do not begin the pan until the swipe fails.
        if gestureRecognizer is UIScreenEdgePanGestureRecognizer && otherGestureRecognizer is UIPanGestureRecognizer {
            return true
        }
        return false
    }
}
```
