### ISSUE TITLE
Cell delegate property name clash

### ISSUE THREAD

**Issue by phillfarrugia** [SwipeCellKit/SwipeCellKit#236]
Problem:
The property name `delegate` on the cell classes (`SwipeTableViewCell` for example) clash with the pattern of `delegate` properties typically used on custom UITableViewCell/UICollectionViewCell subclasses. This becomes an issue when I want my cell subclass to inherit from `SwipeTableViewCell` but I already have my own delegate property. I can't override the inherited delegate property and change it's type in Swift.

Potential Improvements:

1) Change the property name
A potential solution would be to change the name of the `delegate` property on the Cell classes (`SwipeTableViewCell` for example) to something more specific to the framework such as `swipeDelegate`. A user could have their own `delegate` property, and just set a `swipeDelegate` for functionality specific to this framework.

2) Use Protocol Associated Types 
If we defined a protocol which had an associated type, conformers could define their own Delegate type as long as it also conformed to a base type as such the SwipeTableViewCellDelegate.

I'm not sure if either of these are ideal solutions, or even if this is a problem worth fixing. If it's only me, it's fine, but if not - let me know. I'd be happy to implement and submit a PR for review.

**Comment by kurabi** [comment]
Why not just rename your own delegate? This is a breaking change that won’t be considered.

**Comment by antoescu** [comment]
+1
