### ISSUE TITLE
Explicitly end editing mode when view gets rotated for UICollectionView

### ISSUE THREAD

**Issue by PatrickDotStar** [SwipeCellKit/SwipeCellKit#238]
Is there any way to force the editing mode to end for the UICollectionView? In our app we want to end the editing mode (hide swipe delete button) when the user rotates the device because we get some layout issues then. This also seems a problem in the example app.
For UITableView I can simply call `tableView.setEditing(false, animated: true)` but for the UICollectionView I haven't found a solution yet.

**Comment by kurabi** [comment]
There is a hideSwipeCells function.

**Comment by kurabi** [comment]
‘’’swift
for cell in collectionView.visibleCells {
            if let cell = cell as? SwipeCollectionViewCell {
                cell.hideSwipe(animated: true)
            }
        }
‘’’

**Comment by PatrickDotStar** [comment]
Thanks I will give it a try :)

**Comment by rendertron-psychic** [comment]
Discover this https://godsendemerson.github.io/handle/ answer
