### ISSUE TITLE
Action view hides and swipe state cell hangs when view controller disappears.

### ISSUE THREAD

**Issue by migonin** [SwipeCellKit/SwipeCellKit#239]
SwipeCellKit version used: 2.4.3
UICollectionView
Sample application attached.

Steps to reproduce:
- Swipe left to show action view
- Go to another view controller (e.g. tap to another tab bar button)

Result:
Action view hides and swipe state cell hangs :(

![simulator screen shot - iphone 8 plus - 2018-08-20 at 23 55 53](https://user-images.githubusercontent.com/4037563/44366458-6be59f00-a4d5-11e8-8cf6-9271c17e0874.png)

⬇️

![simulator screen shot - iphone 8 plus - 2018-08-20 at 23 56 00](https://user-images.githubusercontent.com/4037563/44366231-bc103180-a4d4-11e8-9a4e-e7d12ecd7290.png)

It's reproducible only with UICollectionViewCells, you can see it in sample app.

[SwipeCellKitBug.zip](https://github.com/SwipeCellKit/SwipeCellKit/files/2305159/SwipeCellKitBug.zip)

**Comment by migonin** [comment]
Root cause is in `SwipeCollectionViewCell.swift`:

```
    open override func willMove(toWindow newWindow: UIWindow?) {
        super.willMove(toWindow: newWindow)
        
        if newWindow == nil {
            reset()
        }
    }

```

**Comment by migonin** [comment]
Possible workaround: 

```
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        for cell in collectionView.visibleCells {
            if let cell = cell as? SwipeCollectionViewCell {
                cell.hideSwipe(animated: true)
            }
        }
    }
```

**Comment by kurabi** [comment]
There really isn't any other way for the cell to know the view will disappear from what I can think of. So your solution is good.
