### ISSUE TITLE
Problem with swipe in iOS 11.4, 2.4.3

### ISSUE THREAD

**Issue by Narrorek** [SwipeCellKit/SwipeCellKit#244]
Hey i have problem with default configuration of SwipeCellkit.
https://streamable.com/kfyuq

Cell code: 

`class ChatTableViewCell: SwipeTableViewCell {

    private static let placeholder: UIImage = #imageLiteral(resourceName: "ic_placeholder")
    private static let providerPlaceholder: UIImage = #imageLiteral(resourceName: "ic_placeholder_provider")

    //Controls containers
    private let leftView: UIView = UIView()
    private let centerView: UIView = UIView()
    private let rightView: UIView = UIView()

    private let avatarView: AvatarView = AvatarView()
    private let authorLabel: UILabel = UILabel()
    private let messageLabel: UILabel = UILabel()
    private let dateLabel: UILabel = UILabel()

    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        self.setup()
    }

    required init(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    //TODO: replace string with model
    public func prepareWith(messageItem: ConversationMO) {

        guard let contact = messageItem.contact else { return }

        if let name = contact.determineNameAndLastName().name,
           let lastName = contact.determineNameAndLastName().lastName {
            self.authorLabel.text = "\(name) \(lastName)"
        }

        self.avatarView.setImage(for: contact.remoteUser?.profilePhoto,
                data: contact.bookUser?.imageData as? Data,
                nameAndSurname: [contact.determineNameAndLastName().name!, contact.determineNameAndLastName().lastName!],
                isProvider: contact.remoteUser?.providerData != nil ? true: false, shouldShowBorder: false)

        //fill content
        if let lastMessage = messageItem.lastMessage,
           let content = lastMessage.content,
           let date = lastMessage.createdAt {
            self.messageLabel.text = content
            if !lastMessage.isRead {
                self.markUnread()
            }
        }

    }

    override func prepareForReuse() {
        super.prepareForReuse()
        self.setup()
    }

    public func setup() {
        self.leftView.addSubview(self.avatarView)
        self.centerView.addSubview(self.authorLabel)
        self.centerView.addSubview(self.messageLabel)
        self.rightView.addSubview(self.dateLabel)

        self.authorLabel.textColor = ColorFactory.taupeGray
        self.messageLabel.textColor = ColorFactory.taupeGray
        self.dateLabel.textColor = ColorFactory.taupeGray
        self.authorLabel.font = FontFactory.author
        self.messageLabel.font = FontFactory.messagePreview
        self.dateLabel.font = FontFactory.messagePreview

        self.contentView.addSubview(self.leftView)
        self.contentView.addSubview(self.centerView)
        self.contentView.addSubview(self.rightView)

        self.contentView.clipsToBounds = false
        self.contentView.autoresizesSubviews = false

        self.setupConstraints()
    }

    public func markUnread() {
        self.authorLabel.textColor = ColorFactory.black
        self.messageLabel.textColor = ColorFactory.black
        self.dateLabel.textColor = ColorFactory.black
    }

    private func setupConstraints() {
        self.leftView.snp.makeConstraints { maker in
            maker.left.equalToSuperview()
            maker.top.equalTo(self.contentView.snp.top)
            maker.width.equalTo(100)
            maker.height.equalTo(self.contentView.snp.height)
         }
        self.rightView.snp.makeConstraints { maker in
            maker.width.equalTo(100)
            maker.height.equalTo(self.contentView.snp.height)
            maker.right.equalTo(self.contentView.snp.right)
         }
        self.centerView.snp.makeConstraints { maker in
            maker.height.equalTo(self.contentView.snp.height)
            maker.left.equalTo(self.leftView.snp.right)
            maker.right.equalTo(self.rightView.snp.left)
        }

        self.avatarView.snp.makeConstraints { maker in
            maker.width.equalTo(60)
            maker.height.equalTo(60)
            maker.center.equalTo(self.leftView.snp.center)
         }

        self.authorLabel.snp.makeConstraints { maker in
            maker.width.equalTo(self.centerView.snp.width)
            maker.top.equalTo(self.centerView.snp.top).offset(25)
            maker.left.equalTo(self.centerView.snp.left)
         }
        self.messageLabel.snp.makeConstraints { maker in
            maker.left.equalTo(self.centerView.snp.left)
            maker.width.equalTo(self.centerView.snp.width)
            maker.top.equalTo(self.authorLabel.snp.bottom)
         }

        self.dateLabel.snp.makeConstraints { maker in
            maker.right.equalTo(self.contentView.snp.right).inset(10)
            maker.top.equalTo(self.rightView.snp.top).offset(25)
        }
    }
}
`

Default configuration for SwipeCellKit and tableView.

Do you have idea what is wrong ? Thanks

**Comment by kurabi** [comment]
Works fine in the example Mail App, please compare with that and see where the issue or error is.
