### ISSUE TITLE
Xcode10 beta6 compilation error

### ISSUE THREAD

**Issue by ATrotsenko** [SwipeCellKit/SwipeCellKit#245]
I'm use cocoapods.
http://prntscr.com/ku9puj

 in Xcode9 everything fine

**Comment by sebasdeweert** [comment]
Also Carthage is not working with Xcode 10 GM

```
*** Building scheme "SwipeCellKit" in SwipeCellKit.xcworkspace
Build Failed
	Task failed with exit code 65:
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/4k/pb54lttd6fd_19j3tf6c3f1m0000gq/T/carthage-xcodebuild.Oq47LW.log
```

**Comment by kurabi** [comment]
Please take a look at the PRs or use the search functionality.

**Comment by sebasdeweert** [comment]
After the swift 4.2 merge, still carthage is not working:
`Checking out SwipeCellKit at "2.4.3"`

It should be version 2.5 right?
