### ISSUE TITLE
Xcode 10 GM Swift Compiler Error

### ISSUE THREAD

**Issue by ArthurMaroulier** [SwipeCellKit/SwipeCellKit#246]
Hi,
We've got two Swift compiler errors "Ambiguous use of 'frame'" in file SwipeController.swift lines 109 and 204.

If we check the box "Continue building after errors" in Xcode preferences we've got two more errors that rely on objective c :
"Could not build Objective-C module 'SwipeCellKit'" when SwipeCellKit is imported in swift file.
And in the generated module.modulemap file we got "Header 'SwipeCellKit-Swift.h' not found".

Xcode 10 GM (Version 10.0 (10A254a))
SwipeCellKit v2.4.3 with cocoapods.

Thanks

**Comment by bettola** [comment]
here as well. need a fix ASAP! :-)

**Comment by kurabi** [comment]
Please take a look at the #213

**Comment by thejeff77** [comment]
Seeing this on 2.7.1 for some reason. 

/Users/username/Library/Developer/Xcode/DerivedData/AppName-bcsqogsyamkqalgkuggzxalocanz/Build/Intermediates.noindex/AppName.build/Debug-iphoneos/AppName.build/DerivedSources/AppName-Swift.h:191:9: Module 'SwipeCellKit' not found

XCode 11.3.1, Swift Package Manager + Carthage

Its weird, it was happening on my branch, then I switched to my base branch, still happening - cleared all project data, restarted Xcode, even force cleaned everything. Its like SPM broke or updated.

Any ideas?
