### ISSUE TITLE
Ambiguous use of 'frame'

### ISSUE THREAD

**Issue by drz01311** [SwipeCellKit/SwipeCellKit#247]
Since iOS 12 is coming in a few days I'm updating my apps to iOS 12. I'm using Xcode 10. I get the error Ambiguous use of 'frame' in SwipeController.swift (Swipe Cell Code Not Created By Me). 

First Error

![snip20180914_1](https://user-images.githubusercontent.com/36215307/45581015-442bf180-b85d-11e8-9aa8-9e3b275d7efa.png)

Second Error

![snip20180914_2](https://user-images.githubusercontent.com/36215307/45581016-442bf180-b85d-11e8-99db-d69951eeab43.png)

Not sure what to do

**Comment by drz01311** [comment]
Thanks for all help!

**Comment by kurabi** [comment]
Please upgrade to v2.5.0

**Comment by drz01311** [comment]
I am currently using v2.5.0

**Comment by kurabi** [comment]
No you are not:
https://github.com/SwipeCellKit/SwipeCellKit/blob/2.5.0/Source/SwipeController.swift

**Comment by drz01311** [comment]
The pictures are outdated. Now I am using 2.5.0. Error is still showing

**Comment by cXode** [comment]
Same problem here. Have you sold it yet?

**Comment by kurabi** [comment]
Please use Xcode 12, and please use Swift 4.2
