### ISSUE TITLE
Error in iOS 12

### ISSUE THREAD

**Issue by BetilloGG** [SwipeCellKit/SwipeCellKit#250]
i have a problem whit iOS 12 and Xcode 10.

 this function not fount.

override var intrinsicContentSize: CGSize {
        return CGSize(width: UIViewNoIntrinsicMetric, height: contentEdgeInsets.top + alignmentRect.height + contentEdgeInsets.bottom)
    }

i`m used this pod.

pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'develop'

and i have the problem.

![captura de pantalla 2018-09-21 a la s 12 04 29](https://user-images.githubusercontent.com/43450363/45895368-a1acca80-bd96-11e8-876c-b8ec10f3da20.png)

![captura de pantalla 2018-09-21 a la s 12 04 39](https://user-images.githubusercontent.com/43450363/45895475-e7699300-bd96-11e8-9ff6-c9b51158c75d.png)
![captura de pantalla 2018-09-21 a la s 12 04 51](https://user-images.githubusercontent.com/43450363/45895477-e7699300-bd96-11e8-8dc5-4b80af4440a8.png)
![captura de pantalla 2018-09-21 a la s 12 04 57](https://user-images.githubusercontent.com/43450363/45895478-e7699300-bd96-11e8-973f-b3dd05440cad.png)

**Comment by kurabi** [comment]
Upgrade your project to Swift 4.2
