### ISSUE TITLE
After including pod SwipeCellKit the app is not going to built

### ISSUE THREAD

**Issue by Gennady77** [SwipeCellKit/SwipeCellKit#252]
Xcode - 9.4.1
Swift - 4.1
iOS - 11.4
![screen shot 2018-10-02 at 12 04 05](https://user-images.githubusercontent.com/854220/46339732-40111980-c63c-11e8-82d9-d307ebb3f812.png)

**Comment by kurabi** [comment]
Read the requirements and install guide in the README
