### ISSUE TITLE
Facing issue with SwipeCellkit pod when building rocketchat ios in swift 4.1 , xcode 4.1

### ISSUE THREAD

**Issue by someshrathi02** [SwipeCellKit/SwipeCellKit#253]
<img width="1183" alt="screen shot 2018-10-19 at 3 05 12 pm" src="https://user-images.githubusercontent.com/26894621/47202770-d4a3a780-d3b0-11e8-953c-777b026b9de1.png">

**Comment by kurabi** [comment]
You are not compiling with Swift 4.1. Double check that plz.
