### ISSUE TITLE
CollectionView scrolling disabled.

### ISSUE THREAD

**Issue by AndreiRybak** [SwipeCellKit/SwipeCellKit#256]
Hi.
I apologize if this question has already been asked.

Inheritance from SwipeCollectionViewCell disables default collectionView scrolling, even if you return nil in _editActionsForItemAt indexPath_:  function.

Is there a simple way, if a cell doesn't have any actions, don't block default scrolling for CollectionView?

Thanks!

**Comment by kurabi** [comment]
I can't reproduce your issue with the example Mail app provided. I attempted to reproduce it by returning an empty `SwipeActions` array, and I can scroll the collection view just fine.

**Comment by AndreiRybak** [comment]
@kurabi 
What about horizontal scrolling. When you have a lane of items and you want to scroll them horizontally, if you have no actions for cell.

**Comment by slauwer** [comment]
Any news on this problem ?
I have some cells that in witch I want to disable the "swipe" ability and others I want to be able to swipe in...

**Comment by kurabi** [comment]
@AndreiRybak In that case, you should provide a different type of cell to the CollectionView.

The `editActionsForItemAt:indexpath:` is to provide temporary way to disable swipe actions. For example, the table/collection view is in an "edit" state where cells should not swipe. This way, if the user try to swipe while the table/collection view, the library continuously monitors if the edit state is no longer in effect.
