### ISSUE TITLE
CollectionView - Row is left blank after action pressed

### ISSUE THREAD

**Issue by muzoman** [SwipeCellKit/SwipeCellKit#259]
Not sure what I'm doing wrong - I've implemented a UICollectionView and experiencing the following problem:

0) Row before swipe:

![img_1113](https://user-images.githubusercontent.com/320009/47967333-16407d80-e054-11e8-8088-6cd4da1bfe41.PNG)
1) Swipe row left and Actions are correctly displayed:
![img_1114](https://user-images.githubusercontent.com/320009/47967337-2193a900-e054-11e8-9565-2146c5812b80.PNG)
2) Press an Action and the area where the Action buttons were goes blank - cell content doesn't animate back:
![img_1115](https://user-images.githubusercontent.com/320009/47967343-2c4e3e00-e054-11e8-9548-2e9eba54241c.PNG)

What am I doing wrong? This is version 2.5.0

**Comment by kurabi** [comment]
Can you compare your code with the example Mail app? Works correctly there.

**Comment by muzoman** [comment]
If you have the SwipedAction hidesWhenSelected  flag set to false then you see the behaviour above the action icons all disappear when one is selected leaving the row content swiped off left. If you set it to true then the row content is correctly animated back.

**Comment by kurabi** [comment]
@muzoman I can't reproduce. I tried `hidesWhenSelected = false` in the mail example app and it works fine. It does not hide when the action is selected, but the actions do not disapear.

Will re-open if you can provide a way to reproduce this. Thanks
