### ISSUE TITLE
Add Shadow and rounded Corners to cell

### ISSUE THREAD

**Issue by noTermMO** [SwipeCellKit/SwipeCellKit#263]
I have my custom CollectionViewCell, based on the SwipeCell, customised with rounded corners and a shadow. How can I solve the problem, that my shadow moves with the cell while swiping?

**Comment by APvanGrootel** [comment]
I have the same problem. I tried using didTransition (inside a DispatchQueue block), but the problem is that didTransition is not being called when you release during swiping.

**Comment by mlyongardiner** [comment]
@dmnjkr  did you figure this out? Wondering if you did because it's closed and I'm trying to figure out how to round the corners of my actions as well, or were you just rounding the corners of the cell itself?
