### ISSUE TITLE
360° phone rotation breaks layout constraints for the "UICollectionView Example"

### ISSUE THREAD

**Issue by igavrysh** [SwipeCellKit/SwipeCellKit#271]
After 360° phone rotation on the sim at "UICollectionView Example", Cell constraints are broken

See the screen below:
![simulator screen shot - iphone x - 2018-12-21 at 11 14 56](https://user-images.githubusercontent.com/10332978/50359467-b7ef3180-0511-11e9-8198-7dc1967509eb.png)

**Comment by kurabi** [comment]
This seems like just an issue with the example app. PRs are welcome.
