### ISSUE TITLE
Swipe Action not complete..

### ISSUE THREAD

**Issue by furqanarda** [SwipeCellKit/SwipeCellKit#273]
In my app, everything is working great. But when i try to delete my row with swipe destructive in simulator, red bar is not completing and my row is not deleting.  Also i tried with my iphone X and same problem.

i attached a screen shot of my simulator. 

<img width="293" alt="screen shot 2019-01-07 at 00 51 30" src="https://user-images.githubusercontent.com/46301281/50742031-e01ba780-1216-11e9-89bb-df4d52072713.png">

**Comment by kurabi** [comment]
Please look at the included Mail App Example.
