### ISSUE TITLE
Cell remains hide after swiping two tableviewCells at same time

### ISSUE THREAD

**Issue by santicarmo31** [SwipeCellKit/SwipeCellKit#275]
I've found an issue where a tableViewCell remains hide after swiping two `tableViewCells` at time. 

All you have to do is press `option` in the keyboard and go to the Example app on **UITableView example** and swipe.

![2019-01-21 15-38-14 2019-01-21 15_41_34](https://user-images.githubusercontent.com/5218843/51498008-0ef75900-1d93-11e9-9eea-1d0162bfd134.gif)

**Comment by kurabi** [comment]
Can you do this in device?

**Comment by santicarmo31** [comment]
> Can you do this in device?

Yes

**Comment by kurabi** [comment]
So what does the option key do exactly, and how do you reproduce that on device?
