### ISSUE TITLE
sourseView and sourceRect for Popover?

### ISSUE THREAD

**Issue by mshibanami** [SwipeCellKit/SwipeCellKit#276]
In iPad, an action sheet of `UIAlertController` requires `sourceView` and `sourceRect` like this:

``` swift
SwipeAction(style: .default, title: "My Action") { (action, indexPath) in
    let alertController = UIAlertController(title: nil, message: nil, preferredStyle: .actionSheet)
    alertController.popoverPresentationController?.sourceView = ...
    alertController.popoverPresentationController?.sourceRect = ...
    ...
    self?.present(alertController, animated: true)
}
```

I'd like to set them for the action's view, but couldn't find a elegant way. What's the best way for that?

**Comment by kurabi** [comment]
In `UITableView` and `UICollectionView`, you can fetch the cell by indexPath, which is the view. Is that sufficient?
