### ISSUE TITLE
Build failure with Xcode 10.2 beta

### ISSUE THREAD

**Issue by corteggo** [SwipeCellKit/SwipeCellKit#278]
SwipeCellKit has some build errors with Xcode 10.2 using Swift 4.2

**Comment by kurabi** [comment]
Fixed #279.

**Comment by ItayAmzaleg** [comment]
> Fixed #279.

What version is the fix?
I'm having build errors on Xcode 10.2 release version,
To be precise to be precise on SwipeController lines 76, 95 swipeable variable should be unwrapped.
Latest pod version, 2.5.1 is from Dec 13, 2018. any pod updates soon?
