### ISSUE TITLE
When using a xib as reusable view, swipe does not push cell content

### ISSUE THREAD

**Issue by brandonscript** [SwipeCellKit/SwipeCellKit#282]
When using a xib reusable view for the collection view, it seems that the cell's content from the xib does not get pushed along with the swipe gesture, and instead the actions are presented on top of the cell's content:

<img width="388" alt="screen shot 2019-02-18 at 2 45 31 pm" src="https://user-images.githubusercontent.com/1480253/52979799-2888c200-338c-11e9-8544-5b8be3fa01a3.png">

Here's a modified version of the sample project where I was able to reproduce this. Any idea what to do to make the cells respond to the swipe gesture?

[SwipeCellKit-develop-brandonscript.zip](https://github.com/SwipeCellKit/SwipeCellKit/files/2877618/SwipeCellKit-develop-brandonscript.zip)

Worth noting that I tried this with a UITableViewCell, and it does behave correctly.

**Comment by bureauvk** [comment]
My actions are presented **below** all content of the cell (its not pushing it away). I am not using a xib File. I subclass SwipeCollectionViewCell.

**Comment by kurabi** [comment]
I suspect for both of you are not adding your views to the cell's `contentView`:
https://developer.apple.com/documentation/uikit/uicollectionviewcell/1620133-contentview

**Comment by brandonscript** [comment]
Admittedly it's been a while since I put that demo together, but I was using IB to demonstrate it, which AFAIK adds everything to the content view of the cell. All I did was take the existing demo implementation of TableViewCells and convert them to CollectionViewCells.

**Comment by kurabi** [comment]
I looked at the view hierarchy and the content is not in the content view.

**Comment by brandonscript** [comment]
Ah, Ok maybe that is it then. Cheers!

**Comment by bureauvk** [comment]
Yes, its working now. Thanks!
