### ISSUE TITLE
delete action threshold

### ISSUE THREAD

**Issue by cleverClosure** [SwipeCellKit/SwipeCellKit#284]
Hi. You need to move your finger all the way to the left/right edge of a cell in order to delete it. Is there a way to invoke delete action by paning just slightly beyond the center of a cell? To make it easier to delete.

**Comment by kurabi** [comment]
The default values match the preloaded iOS apps like Mail, etc. You can customize this. Please take a look at the Advanced.md

https://github.com/SwipeCellKit/SwipeCellKit/blob/develop/Guides/Advanced.md
