### ISSUE TITLE
minimumButtonWidth

### ISSUE THREAD

**Issue by lsmilek1** [SwipeCellKit/SwipeCellKit#287]
HI!

I wonder if you could implement an option to set a minimum button width? If I understand it all correctly, then minimum width is hard coded 74pt. I found a line #134 in the pod file swipeActionView.swift, where I can adjust it and it works fine. But after update of the pod, if jumps back. It would be convenient to have it controlled by the app code. 

`let maximum = options.maximumButtonWidth ?? (size.width - 30) / CGFloat(actions.count)
        let minimum = options.minimumButtonWidth ?? min(maximum, 50)
        minimumButtonWidth = buttons.reduce(minimum, { initial, next in max(initial, next.preferredWidth(maximum: maximum)) })`

Thank you for consideration! No priority, just an input for enchantment!

**Comment by kurabi** [comment]
The default is 74 **if** no minimumButtonWidth is set in the options.
`let minimum = **options.minimumButtonWidth** ?? min(maximum, **74**)`
