### ISSUE TITLE
Keep swipe state of cell when reload data of collectionview

### ISSUE THREAD

**Issue by phongtran92** [SwipeCellKit/SwipeCellKit#288]
Hi,
Is there any way to keep the swipe state of cell when the collection view reloadData ?
I can do it with tableview by override prepareForReuse() and do nothing in it 
But that way is not work with collection view

Please help me, 
Thanks

**Comment by kurabi** [comment]
Please don't override `prepareForReuse` without calling super, this will have unintended side effects. Use insert/delete rows/cell instead of reloadData if you want to preserve swipe state.

**Comment by acecilia** [comment]
In a collectionView, I am experiencing the following:
* I have a section 1, with no cells swiped
* I have a section 2, with one cell swiped
* When I call `reloadSections` for section 1, the swiped cell in section 2 looses the swipe state

Any hint or idea why is this happening? 🙏 Thanks!
