### ISSUE TITLE
Optional Type error

### ISSUE THREAD

**Issue by Joshandrews43** [SwipeCellKit/SwipeCellKit#290]
Just downloaded the new XCode tools, and now this is giving me an error:

` if let swipeable = scrollView?.swipeables.first(where: { $0.state == .dragging }) as? UIView, swipeable != self.swipeable {`

It says that `swipeable != self.swipeable` : "value of optional type (UIView & Swipeable)? must be unwrapped to a value of UIView & Swipeable"

Anyone else?

**Comment by indirect** [comment]
Changing it to `swipeable != (self.swipeable ?? nil)` worked for me.

**Comment by psi-gh** [comment]
Have same errors. Why is the upgrade of xCode caused it? Even swit version stays the same.

**Comment by psi-gh** [comment]
Install SwipeKit like this
pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :commit => '9bd4543ebd4d7f104b2c4d732782e330500da220'

it will give xCode 10.2 compatibility. Temporary solution though. Waiting for new version! :)

**Comment by bettola** [comment]
Same error here

**Comment by reshadf** [comment]
Same error on xcode 10.2

**Comment by dmi3j** [comment]
This become urgent for Xcode 10.2 and Swift 5

**Comment by kurabi** [comment]
We also had a branch for Xcode 10.2 support. Now that branch is merged with master and has been deployed to cocoapods. Enjoy.
