### ISSUE TITLE
Carthage update error

### ISSUE THREAD

**Issue by riki-dexter** [SwipeCellKit/SwipeCellKit#291]
Hi, I'm running carthage update command with new Xcode 10.2 installed but i'm getting this terminal error:

`Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /path/to/app/AppName/Carthage/Checkouts/SwipeCellKit/SwipeCellKit.xcworkspace -scheme SwipeCellKit -configuration Release -derivedDataPath /Users/ricdes/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/SwipeCellKit/2.5.1 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/gm/6120_d956w927bb5y07w2cth0000gn/T/SwipeCellKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO`

Thank you

**Comment by juanjoseluisgarcia** [comment]
This is the same as Issue #289
