### ISSUE TITLE
Swift 5 Support w/ Cocoapods

### ISSUE THREAD

**Issue by jlaws** [SwipeCellKit/SwipeCellKit#292]
## Expected Results

No warning to convert SwipeCellKit.framework to Swift 5

## Actual Results

Xcode created warnings to convert SwipeCellKit.framework to Swift 5

## Steps to Reproduce

Build the cocoapod in Xcode 10.2

**Comment by jschwendt** [comment]
+1

**Comment by loloabj** [comment]
For Swift 5.0
I had to make 2 edits on SwipeController.swift
-> replaced `self.swipeable`  by `self.swipeable ?? nil` on lines 76 & 95
Not sure this is the best fix...

**Comment by kreeger** [comment]
I've opened #294 for this!

**Comment by CuongCro** [comment]
Add this to podfile:

pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'xcode_10.2'

After that the issues  should be solved with cmd+B. It definitely worked for me.

**Comment by kurabi** [comment]
v2.5.2 now supports Xcode 10.2 and is comparable with Swift 5. Not much is required to make the library use swift 5, but that will be a follow up release. Let me know if you have any other issues.

**Comment by jlaws** [comment]
XCode is still complaining about upgrading the library to Swift 5, I'll create a new Issue to track that
