### ISSUE TITLE
Multiple selection

### ISSUE THREAD

**Issue by mihailsalari** [SwipeCellKit/SwipeCellKit#293]
Hello,
I tried to add:
    tableView?.allowsSelection = true
    tableView?.allowsMultipleSelectionDuringEditing = true
but the checkmark isn't selected, how to fix?

**Comment by kurabi** [comment]
SwipeCellKit doesn't deal with cell selection.

**Comment by ronysteel** [comment]
You have no idea how to fix and why that you close this issue with this answer. But I found how to fix it.

**Comment by mihailsalari** [comment]
@kurabi. I already fixed it. Thank you for your help and understanding. You're a "great" professional.
