### ISSUE TITLE
clear swipe state when go to different view controller or switch between segment control

### ISSUE THREAD

**Issue by lephillips** [SwipeCellKit/SwipeCellKit#299]
Hello, I'm running in this problem where I swap the collectionView cell and not click delete, go to a different tab or viewController, and go back the swipe state still there but the delete red background and icon disappear. Is there a way to clear the swipe state when switch to another view. 

I already try this answer from #239 
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        for cell in collectionView.visibleCells {
            if let cell = cell as? SwipeCollectionViewCell {
                cell.hideSwipe(animated: true)
            }
        }
    }

but it didn't work, I put breakpoint and the func didn't even called when I switched views.
Any method to clear out the swipe state? 

![Screen Shot 2019-03-28 at 1 33 25 PM](https://user-images.githubusercontent.com/48699418/55193663-dd20bb00-5164-11e9-9903-68aff7a3c2a0.png)
![Screen Shot 2019-03-28 at 1 42 06 PM](https://user-images.githubusercontent.com/48699418/55193664-dd20bb00-5164-11e9-8084-0d3c557acc55.png)

**Comment by kurabi** [comment]
If your `viewWillDisappear` isn't being called, then you have an issue with how your child view controllers are setup and how you are switching between them.

**Comment by mortenholmgaard** [comment]
@lephillips Did the code work when you ensured that `viewWillDisappear` was called? It does not work for me as the cell appear to have the state centered even though it is as on your screenshot.
