### ISSUE TITLE
Missing tag for version 2.6.0

### ISSUE THREAD

**Issue by julienpouget** [SwipeCellKit/SwipeCellKit#306]
Hi,

It looks like the tag of the 2.6.0 version is missing. Could you please create it on the repo so we can get the latest version with CocoaPods.

Thanks,
Julien

**Comment by kurabi** [comment]
Version 2.6.0 was being prepared in `develop` branch. Was waiting for the Xcode 10.2 changes/issues to settle as there wasn't an immediate need to switch library to use Swift 5 as it was compatible with Swift 5 apps. In any case, I just released it.
