### ISSUE TITLE
Collection view gestures breaking

### ISSUE THREAD

**Issue by jangsy7883** [SwipeCellKit/SwipeCellKit#308]
I'm noticing strange behavior after the Extensions method "setGestureEnabled" gets called. It seems to break all tap gesture recognition.

https://github.com/SwipeCellKit/SwipeCellKit/issues/56
There was a similar issue of UITableView.
I think that UICollectionView should be modified in the same way as UITableView.

What do you think?

and thanks for making good open source!

**Comment by kurabi** [comment]
What issue are you facing exactly?
