### ISSUE TITLE
still can't fix this swipe problem

### ISSUE THREAD

**Issue by thoughtcastdavid** [SwipeCellKit/SwipeCellKit#310]
@sgruby @kurabi @jerkoch @caffeineflo @zssz  ------ im trying to prevent my cell from sliding off the screen completely, i've posted twice here, once i was reffered to the sample app then i was referred to a piece of code that i couldn't figure out what to do with.. can someone please show me an example of how to configure my cell to avoid this dissapearence?

**Comment by caffeineflo** [comment]
I don't think that's the way to get your issue solved. But how about pointing out these other two places you were referred from first and explain your issue in greater detail than making us search?

**Comment by thoughtcastdavid** [comment]
@caffeineflo  - https://github.com/SwipeCellKit/SwipeCellKit/issues/269 - https://github.com/SwipeCellKit/SwipeCellKit/issues/309 - 
![IMG_909FD141E6E0-1](https://user-images.githubusercontent.com/42627029/56989369-25a60c80-6b47-11e9-9d5d-55b6b082d8d6.jpeg)

as you can see, the contents of the cell are compeltely gone when i swipe the cell... i need the contents to remain

**Comment by kurabi** [comment]
Sorry this is not supported.
