### ISSUE TITLE
Invalid update: invalid number of rows in section 0

### ISSUE THREAD

**Issue by Saursinet** [SwipeCellKit/SwipeCellKit#313]
I got two SwipeActions in my cells one to delete and one to modify. The one to modify does perform a segue with a modal view and the one to delete does display a popup to make sure the user want to. Whichever SwipeAction I put first in the return value will make the app crash. But the second one will always works. So I don't think the problem is with my actions because they work if they're not on the right side of the swipeActions. 
I saw another ticket to which you answered see the example with Mails but there is no pop up from the first swipeAction it's on the first one.

Here is the code :
`    func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
        guard orientation == .right else { return nil }

        let edit = SwipeAction(style: .default, title: nil) {action,
            indexPath in
            self.modifyPatientView(patient: self.patients[indexPath.row])
        }
        edit.hidesWhenSelected = true
        configure(action: edit, with: .edit)
        
        let cell = tableView.cellForRow(at: indexPath) as! PatientTableViewCell
        let closure: (UIAlertAction) -> Void = { _ in cell.hideSwipe(animated: true) }
        let delete = SwipeAction(style: .default, title: nil) { action, indexPath in
            let alert = UIAlertController(title: "Suppression patient", message: "Êtes-vous sur de vouloir supprimer ce patient ?", preferredStyle: .alert)
            alert.addAction(UIAlertAction(title: "OK", style: .default, handler: closure))
            alert.addAction(UIAlertAction(title: "Annuler", style: .cancel, handler: nil))
            
            self.present(alert, animated: true, completion: nil)
        }
        configure(action: delete, with: .trash)

        return [delete, edit]
    }`

On this case the delete button will make the app crash and if I `return [edit,delete]` then edit will crash.

**Comment by kurabi** [comment]
What does the crash say?

**Comment by Saursinet** [comment]
The all crash is 
``
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (3) must be equal to the number of rows contained in that section before the update (3), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'
``

**Comment by kurabi** [comment]
You are not correctly removing the row from your dataset. In other words, your table view has 3 rows before and after the update even though you asked the table view to delete a row, hence you didn't remove that row from your dataset.

**Comment by Saursinet** [comment]
But the all point is to not delete it right away but add an alert making sure the user want to delete the row. So yeah the row is not deleted it's waiting for the user to confirm.

**Comment by kurabi** [comment]
Got it. Then don't use the `.destructive` style. And delete the row your self when the user confirms deletion.

**Comment by Saursinet** [comment]
Okay I'll give it a try thank you!

**Comment by Saursinet** [comment]
But then as shown by the code I posted earlier my SwipeAction is not in `.destructive` and I still got the error.
``
let delete = SwipeAction(style: .default, title: nil)
``
Can you explain why?

**Comment by kurabi** [comment]
SwipeCellKit only deletes a row on `.destructive`. So your code must be deleting the cell without updating the datasource.

**Comment by Saursinet** [comment]
I understand that but when I move the delete and the edit as returning them like this `return [edit, delete]` then the delete works with the alert. It doesn't work only when it's the first item to be returned.

**Comment by Saursinet** [comment]
@kurabi any news?

**Comment by palla89** [comment]
Same problem here. Not working when an alert is called from the swipe action because the action fulfills before the alert is shown

**Comment by palla89** [comment]
Also @kurabi, I tried again with the example you provided and the issue is exactly the one that @Saursinet described: it does crash only if the alert is the only option. In your MailTableViewController i deleted the delete and flag actions and it crashed. Do you have any idea what could it be?

**Comment by palla89** [comment]
I understood what happens. For some reason, even if the action style is set on 'default', if I put breakpoint on line 421 of SwipeController, you can see that even if I didn't set the destructive/delete action for my alert controller, it executes the code as the deletion one.
I "solved" it for my objective changing the expansionStyle in my controller to .selection instead of destructive, then in your SwipeControlle.swift at line  386 I changed the `perform(action: action, hide: true)` to `performFillAction(action: action, fillOption: .automatic(.reset, timing: .after))`

If I'll have more time to look at it I'll open a PR, but hope this can help others.

**Comment by Evolgence** [comment]
let delete = SwipeAction(style: .destructive, title: nil) { action, indexPath in
                //self.emails.remove(at: indexPath.row)
                print("indexPath.row \(indexPath.row)")
                self.deleteTheHistory(indexPath)
                **action.fulfill(with: .reset)**
            }

**Comment by petrakovpk** [comment]
> let delete = SwipeAction(style: .destructive, title: nil) { action, indexPath in
> //self.emails.remove(at: indexPath.row)
> print("indexPath.row (indexPath.row)")
> self.deleteTheHistory(indexPath)
> **action.fulfill(with: .reset)**
> }

THANK YOU A LOT!! It's work for me!!
