### ISSUE TITLE
didSelectRowAt not being Called

### ISSUE THREAD

**Issue by Sanunez** [SwipeCellKit/SwipeCellKit#315]
# didSelectRowAt not being called
## What's Working right
I have a tableView in a ViewController, I'm fetching data from a database then once the data is finished loading I set the datasource for the table. I then reload the table to display what's on it. I then add the EditAction for the row, and that shows up fine, swipes, and executes correctly.  

## What's not working
When I try to click on a cell, the didSelectRowAt tableView function is not being called. This is shown by the debugger not breaking and Console not showing printed message.

## What I'm trying to do
I'm trying to make it so when the cell is clicked the EditAction  is programmatically called and animated into view

## Hypothesis
I've seen that there has been a similar issue when two different types of Cells are being added to the table, but I'm only adding my custom ProductCell to the table. When I checked the Email Example I noticed it was using a TableViewController and in that project the function gets called no problem. Could the issue be the Controller itself?

# My Environment
Xcode Version:  10.2
Swift Version: 4.2
Deployment Target: 11.0
SwipeCellKit Pod: ``` pod 'SwipeCellKit', '2.5.4' ```
### Custom Cell Class
``` swift
import UIKit
import SwipeCellKit
class ProductCell: SwipeTableViewCell {
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var logoImage: UIImageView!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var priceLabel: UILabel!
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
    }
    override func setSelected(_ selected: Bool, animated: Bool) {
        super.setSelected(selected, animated: animated)
    }
}
```

### ViewController
``` swift
import UIKit
import SwipeCellKit
class ViewController: UIViewController{
  @IBOutlet weak var newTable: UITableView!
  var productArray = [Item]()
  override func viewDidLoad() {
    super.viewDidLoad()
    getItemValues()
  }
  func getItemValues(){
    /* 
    ...
    */
    self.populateDynamicTable()
  }
  func populateDynamicTable(){
    newTable.dataSource = self
    newTable.reloadData()
  }
}
extension ViewController: UITableViewDelegate, UITableViewDataSource, SwipeTableViewCellDelegate{
  func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    print("CLICK")
    let cell = tableView.cellForRow(at: indexPath) as! ProductCell
    cell.showSwipe(orientation: .right, animated: true, completion: nil)
  }
  func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
    return productArray.count
  }
  func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let homeCell = newTable.dequeueReusableCell(withIdentifier: "homeCell") as! ProductCell
    /*
    Initialize Cell
    */
    homeCell.delegate = self
    return homeCell
  }
  func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
    guard orientation == .right else { return nil }
    let add = SwipeAction(style: .default, title: "ADD") { (action, indexPath) in
      print("Adding Element" + self.productArray[indexPath.row].name)
    }
    add.backgroundColor = UIColor(red:0.30, green:0.69, blue:0.31, alpha:1.0)
    return [add]
  }
}
```

**Comment by Sanunez** [comment]
Have already tried ``` newatable.allowSelection = true ``` and table is still unresponsive

**Comment by Sanunez** [comment]
Found the problem, was not setting delegate for the tableView, needed to add
``` swift
func populateDynamicTable(){
    newTable.delegate = self   //<-------THIS IS WHAT I WAS MISSING
    newTable.dataSource = self
    newTable.reloadData()
  }
```

**Comment by caioteodoro** [comment]
Dear Goodness, I've been reading like 15 forum posts so far trying to find why my code wasn't working. TG you posted this! Even though no one replied you, you did make me notice in mine what I needed to. Thank you so much for sharing!!
