### ISSUE TITLE
Swipe menu doesn't show buttons/actions after swiping other cells

### ISSUE THREAD

**Issue by boherna** [SwipeCellKit/SwipeCellKit#318]
This is exactly the same issue reported before on https://github.com/SwipeCellKit/SwipeCellKit/issues/97 but in this case with UICollectionView. Can the same fix applied for the UITableView be used on this case too?

**Comment by kurabi** [comment]
Give me a try and I can review the PR if you think the solution is the same. Thanks.

**Comment by boherna** [comment]
After checking the fixes applied for similar reported issues I realised that the problem was due to using **contentView.clipsToBounds = true** in the awakeFromNib() and by removing it the issue is now gone.
