### ISSUE TITLE
Not pinning to cell's edge

### ISSUE THREAD

**Issue by DamianSzejnoch** [SwipeCellKit/SwipeCellKit#319]
How I can fix this problem? Im using collection view. I would like to pin it from right edge of cell. It's also not hiding cell behind left edge.

<img width="338" alt="Zrzut ekranu 2019-05-28 o 20 12 39" src="https://user-images.githubusercontent.com/44338496/58501539-fbb32a80-8184-11e9-8994-bffae5e26d4e.png">
in

**Comment by kurabi** [comment]
Put your content in the contentView.

**Comment by DamianSzejnoch** [comment]
Ok, now thats above cell but still not moving
