### ISSUE TITLE
Cell is not moving

### ISSUE THREAD

**Issue by DamianSzejnoch** [SwipeCellKit/SwipeCellKit#320]
Cell not moving when tried to swipe. Like on screen below
<img width="1230" alt="Zrzut ekranu 2019-05-29 o 11 41 17" src="https://user-images.githubusercontent.com/44338496/58546985-cea75c00-8206-11e9-9865-ea23db993cf6.png">
<img width="304" alt="Zrzut ekranu 2019-05-29 o 11 42 46" src="https://user-images.githubusercontent.com/44338496/58547020-e252c280-8206-11e9-8545-7c3ae0716781.png">

**Comment by kurabi** [comment]
Put your content in the contentView. See example Mail app.
