### ISSUE TITLE
Swiping full width does not perform delete.

### ISSUE THREAD

**Issue by netsmith** [SwipeCellKit/SwipeCellKit#321]
All working great and still is apart from one problem, I've managed to do something with my code which has stopped the 'swipe right across to delete in one action' feature. The swipe left and right work fine and if I click the icons, including delete everything performs as expected. Its just the full swipe I seem to have broken. I say broken because it was working but I broke it when creating my own custom cell programmatically instead of via the story board, as a subsclass of SwipeTableViewCell.

Is there a property I need to explicitly set? 

Thanks

**Comment by netsmith** [comment]
Just for a little more background, I've noticed that the coloured region on stretches to about halfway, then snaps back, rather than snapping to the full width of the screen, so I'm guessing its something to do do with widths?

**Comment by kurabi** [comment]
Look at the example app.

**Comment by netsmith** [comment]
Any clues as to where to start looking? Like I said it was working and is working now just not for the full swipe across? Im at a loss so any help would be great @kurabi

**Comment by keithmichelson** [comment]
@netsmith It as confusing for me too. This is what did it.
`func tableView(_ tableView: UITableView, editActionsOptionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> SwipeOptions {
        var options = SwipeOptions()
        options.expansionStyle = .destructive
        options.transitionStyle = .border
        return options
    }`

and make sure and call 
`action.fulfill(with: .delete`
when you update the model
