### ISSUE TITLE
iOS 13 compatability

### ISSUE THREAD

**Issue by DarrenAndes** [SwipeCellKit/SwipeCellKit#324]
I am using Xcode 10.2 / Swift 4.2 / SwipeCellKit 2.5.4 with UICollectionViewCells.

The same app that works with swipeKit on iOS 12 doesn't appear to be working on iOS 13 beta 3.

Is this a known issue? Thanks

**Comment by kurabi** [comment]
PRs for iOS 13 are welcome.

**Comment by degello** [comment]
I can confirm that this still is an issue on iOS 13 beta 5 (SwipeCellKit 2.5.4)
Running the app through Xcode 10.2 and 11 gives the same result.

**Comment by AAAstorga** [comment]
Are there any updates on this? I tried digging into the code but I have no idea why this suddenly stopped working on iOS 13?

**Comment by lsmilek1** [comment]
Hey,

I might ask in other words... Does Kurabi update the kit in near future? As “PRs for iOS 13 are welcome” can be understood also “if you want you can update it for iOS 13, I won’t in comming years”

Thanks for update!

**Comment by kurabi** [comment]
The latest iOS 13 Beta 8 has no issues with SwipeCellKit from what I have seen.

**Comment by tulusheg** [comment]
Hello @kurabi,

Have iOS 13.1 beta. Issue is still present. No swipe on iOS 13 but works fine on iOS 12.4 if app was build with Xcode 10.3. If app was build with Xcode 11 beta - swipe works.

**Comment by kurabi** [comment]
>Hello @kurabi, ...

@tulusheg have you tried 13.0 Beta 8? My understanding is 13.1 is a fork of an earlier 13.0 Beta that does NOT have all fixes that are in the 13.0 Beta bass on several user reports.

**Comment by tulusheg** [comment]
@kurabi Sorry, can't test with iOS 13.0 Beta 8 right now. But tested with iOS 13.1 beta 2 and it's still the same. Probably will wait till iOS 13.0 GM or Release to verify there

**Comment by joeboyscout04** [comment]
I tested it with iOS 13.0 Beta 8 and it doesn't seem to work for me either.  This is using Xcode 10.2 built app.
