### ISSUE TITLE
Cells twitching

### ISSUE THREAD

**Issue by vorobyeva-lika** [SwipeCellKit/SwipeCellKit#327]
Hey, I have an issue that also reproducible in your MailExample.
 Cell swipe right is disabled, and cell not twitching at the beginning. 
Swipe the cell from left to right to close Delete button, so that the empty area appears on the left.  Now cell can be swiped right, if try to swipe right again immediately.
 Reproduced both for collection and table view.

![swiperightbug](https://user-images.githubusercontent.com/36149535/61716070-8fba0080-ad88-11e9-8355-2e39ccd5ca6a.gif)

**Comment by kurabi** [comment]
I can’t reproduce this on device. Did you try on device instead of simulator?

**Comment by vorobyeva-lika** [comment]
Yes, I did. 
Reproduced on iOS 11, 12 the same way. 
I didn't check it on iOS 10.

**Comment by kurabi** [comment]
The bounce-back effect is on there on purpose when swipe actions are closed. Once the animation finishes, you can no longer trigger the bounce effect.
