### ISSUE TITLE
How to stop multiple cells from being shown in expanded state

### ISSUE THREAD

**Issue by PawanAhire** [SwipeCellKit/SwipeCellKit#329]
I've added SwipeCellKit to my tableview. When I swipe on one cell it remains in expanded state even though I swipe another cell. Because of this, multiple cells are shown in expanded state at the same time.
Please refer attached video recording for proof. 
I have downloaded the demo as well. The issue is reproducible in the demo also.

[Multiple cells are getting swipe issue.mov.zip](https://github.com/SwipeCellKit/SwipeCellKit/files/3456446/Multiple.cells.are.getting.swipe.issue.mov.zip)

**Comment by kurabi** [comment]
This issue doesn’t occur in the sample app. Please take a look at that.

**Comment by PawanAhire** [comment]
Yes it is occurring in sample app too. Please look at attached video in
issue attached in .zip format.

**Comment by kurabi** [comment]
Just tested with Xcode 10.2.1 (Latest) with iOS 12 on device. I do to see the issue.

**Comment by saraperic13** [comment]
This is still an issue. You can achieve this on a physical device with two fingers (or more) dragging at the same time (at exact moment when one cell is being closed, dragging with two fingers different cells). Xcode 12.5, iOS 14.5.1
