### ISSUE TITLE
How can we get any cell opened or not? 

### ISSUE THREAD

**Issue by fcoskun** [SwipeCellKit/SwipeCellKit#331]
How can we get any cell in our tableview is opened or not?  I didnt see any property or function for that.

**Comment by kurabi** [comment]
`tableView.swipeCells()`

**Comment by fcoskun** [comment]
i get Value of type 'UITableView?' has no member 'swipeCells' 

there is no method like swipeCells().

**Comment by kurabi** [comment]
```
for cell in tableView.visibleCells {
    if let cell = cell as? SwipeTableViewCell {
        cell.hideSwipe(animated: true)
    }
}
````

**Comment by fcoskun** [comment]
i only want to reach if any cell swiped or not. 

like this
![image](https://user-images.githubusercontent.com/5501129/62680530-18a77d80-b9c0-11e9-8aee-3ab56470ad35.png)

if anyone is opened as above i want to get a boolen value.

**Comment by fcoskun** [comment]
Hey, 

Is there any way for that?
