### ISSUE TITLE
Loading data to cell which inherits from SwipeTableViewCell

### ISSUE THREAD

**Issue by Linkadi98** [SwipeCellKit/SwipeCellKit#334]
Hi, thanks for creating lib! 
I have big problem here, when fetching data from api, then show it on cell above, no data shows on, but when cell doesnt inherit SwipeTableViewCell, everything works fine, and some weird behaviors when I add your lib to my project, there are:
- No Skeleton loading anymore (confict)
- UILabel in some views disapear (I dont know why)

Thank you for pay attention!

**Comment by kurabi** [comment]
I am not sure what skeleton loading is and what you mean by UILabel disappear.
