### ISSUE TITLE
Programatically calling an Cell's Action/s for Testing

### ISSUE THREAD

**Issue by alihen** [SwipeCellKit/SwipeCellKit#338]
Is there perhaps a way to call a `SwipeCollectionViewCell`'s defined actions in order to test the result of calling the handler?

I noticed that a `SwipeCollectionViewCell` has `actionsView`, which has a function that can tap an action, but I'm unable to access these within a test.

**Comment by kurabi** [comment]
Use the `showSwipe:..` on `SwipeCollectionViewCell` to present the actions. To select one, use the accessibility API to invoke the desired action. Make sure you are setting the `accessibilityLabel` on your `SwipeAction` correctly.
