### ISSUE TITLE
UITableViewCell still there after delete

### ISSUE THREAD

**Issue by palla89** [SwipeCellKit/SwipeCellKit#340]
Hi there!
I have a problem while deleting cells: the UITableViewCell I deleted is still there also after delete. (Graphically I can't see the cell, but it's still there if i debug the code after the last line)

A little context: I have a tableView with custom cells, every cell has 3 uitextfields. I want that pressing Next on the keyboard, the next field is selected, if the fields in that cell are finished, the app should automatically go to the next cell. I implemented it with tags and it works fine, but because of the tag system, I must update the tags after I delete a cell, or the next button wouldn't work.

I did that with this code:

`let deleteAction = SwipeAction(style: .destructive, title: nil) { action, indexPath in

                do {
                    let item = self.items[indexPath.row]
                    self.items.remove(at: indexPath.row)
                    try Environment.itemManager.deleteItem(id: item.id)
                    action.fulfill(with: .delete)
                    self.reorganizeOrderItemTags() //code where I reassign tags, it's a simple for cycle
                } catch {
                    debugPrint(error.localizedDescription)
                }`

Everything seems to be working graphically, but when I debug it, after the action.fullfil(with: .delete) line, I can see that the UITableViewCell I removed, is still there, even if I can't see it.
If I do a reloadData after the fulfill, the cell isn't there anymore. Am I doing something wrong or missing something? 😭

**Comment by kurabi** [comment]
I don’t know what you mean by “it is still there”. Maybe you are holding a reference to it. Please have a look at the example app as a reference.

**Comment by palla89** [comment]
I tried just now with the example and it gives me the same problem, maybe it could be something related to tags and not to SwipeCellKit, I'll explain how to reproduce it:

In the mail example app, in the cellForRowAtIndexPath method, put `cell.tag = 1000 + indexPath.row` just so that it doesn't conflict with anything else, then delete for example the third cell, the one with "Instagram" as from field.
Graphically it's all ok, and also the emails datasource is fine.
But if you put a breakpoint where you do prefer after the delete, (for example I added in the cellForRowAtIndexPath and scrolled table to trigger it), check this from the debugger:

`po (view.viewWithTag(1002) as! MailCell).fromLabel.text`and you'll see that the MailCell is still there! 
I obviously saw this just because I used tags, but maybe as I told before it's not SwipeKit (that I love, of course 💘 )

**Comment by kurabi** [comment]
You are likely holding a reference to the cell somewhere. I don't see any cells leaking (memory leak) in the example app.

**Comment by palla89** [comment]
Hi, have you tried what I wrote in the last comment? Because apart from setting the tag I didn't change anything in the example app

**Comment by kurabi** [comment]
> Hi, have you tried what I wrote in the last comment? Because apart from setting the tag I didn't change anything in the example app

UITableView cell keeps a select number of cells around for cell reuse to reduce memory allocation/deallocation overhead. So yes, your cell will stick around after being deleted because its owned by UITableView.
