### ISSUE TITLE
Swipe Actions Overlay Each Other...

### ISSUE THREAD

**Issue by mechmatt01** [SwipeCellKit/SwipeCellKit#342]
Hello! First off, I would like to say thank you for your fantastic work. More recently, I have encountered this issue, and I can't seem to figure it out. I am using a tableView and when I swipe on it the actions that looked normal for about the last six months have just started overlaying each other, and I can't seem to figure out why. 

[Video](https://www.dropbox.com/s/k5ka0clidlxaw0z/CellsVideo.MP4?dl=0)

As you can see in the video, there are two more actions behind that one, but it seems as if they are all confined to that first and foremost action.  Any ideas? This occurs on iOS 13 as well as 12. I am using Xcode 10.3.

**Comment by uniqby** [comment]
+1 same issue

**Comment by kurabi** [comment]
Are you using UICollectionView or a UITableViewCell?

**Comment by kurabi** [comment]
Please post a sample project up that has the issue so I can try to debug it.

**Comment by kurabi** [comment]
Will reopen if you can provide a test app that demonstrates this.

**Comment by mechmatt01** [comment]
@kurabi So I made a sample project but the issue does not occur on that. So you must think "oh so it's my issue not yours" which you may be correct about. But I can not seem to figure this one out. I have tried debugging it and it does not help. What is weird is when I have 1 cell-like an example cell in the tutorial and I swipe on it... it works just fine but then when the cells load from Firebase it does what you see in that video. I know you are thinking "So what do you want me to do kid?" and my response to that would be "I am not sure" but if you could just take the time to at least possible screen share at some point for just 30 min max and take a look at this to help me out I would so grateful as I can not seem to figure it out and respectfully speaking it did not occur a few months back but I tried downgrading the pod version and that did not help either.
