### ISSUE TITLE
Package.swift

### ISSUE THREAD

**Issue by marcocattai** [SwipeCellKit/SwipeCellKit#343]
This file  is using Swift tools version 3.1.0 which is no longer supported.

Consider using '// swift-tools-version:5.1' at the beginning of the file to specify the current tools version 

See Documentation here -> https://developer.apple.com/documentation/swift_packages/creating_a_swift_package_with_xcode

**Comment by kurabi** [comment]
There is already a PR for this that will be merged now that the GM is out.
