### ISSUE TITLE
Compilation error After importing the library with Swift Pack Manager

### ISSUE THREAD

**Issue by marcocattai** [SwipeCellKit/SwipeCellKit#346]
I have an hybrid project which is using both ObjectiveC + Swift on Xcode 11 GM

Module 'SwipeCellKit' not found in the autogenerated file **My-Project-swift.h**

Any idea?

**Comment by kurabi** [comment]
This project does not support objective-c **based** projects, as it uses Swift constructs not supported by objective-c.

**Comment by marcocattai** [comment]
it is 7 months that I am using it in my hybrid project and it works amazingly - I simply created a wrapper to your classes

**Comment by kurabi** [comment]
Cool, the wrapper is swift based?

**Comment by marcocattai** [comment]
Yes, the wrapper is swift based

**Comment by kurabi** [comment]
So your issue is in a forked version of this library?

**Comment by marcocattai** [comment]
no - In my project, Datasource and cells are swift classes - the viewModel which is using the datasource is still an objectiveC class (it has not been ported yet). Your lib works perfectly also in hybrid projects as soon as you import SwipeCellKit module in Swift classes only. I don't understand why the import is included in the ObjC auto Generated Interface . I am using another project from gitHub which is DeepDiff . It is pure swift and I don't have the same issue with that library.

I was wandering if you have any idea?

**Comment by kurabi** [comment]
In that case you should NOT generate a bridging header since `My-Project-swift.h` looks like a bridging header.

**Comment by marcocattai** [comment]
yes, it is a bridging header

if I include your project using cocoapods it works perfectly - 
If I import the project using swift pack manager it doesn't.

Will try to understand why and then I will post the solution. In the meantime, if you have any idea please let me know

**Comment by kurabi** [comment]
Thats my point, you cannot generate bridging header for SwipeCellKit.

**Comment by alinfarcas12** [comment]
> it is 7 months that I am using it in my hybrid project and it works amazingly - I simply created a wrapper to your classes

Hello! Can you show me an example of the wrapper? I have the same issue
