### ISSUE TITLE
is the last version only suport ios13? some color is dark mode only 

### ISSUE THREAD

**Issue by nirvana72** [SwipeCellKit/SwipeCellKit#347]
![image](https://user-images.githubusercontent.com/15214079/65070151-aebac480-d9be-11e9-9d05-827b811eb7e1.png)

i googled the color name , some one said its used in dark mode

**Comment by kurabi** [comment]
You must use Xcode 11. If you are using an older version of Xcode, please use an earlier version of SwipeCellKit as indicated in the README.md
