### ISSUE TITLE
SwipeActionsView is not shown in iOS 13:bug:

### ISSUE THREAD

**Issue by tarasevchenko** [SwipeCellKit/SwipeCellKit#349]
Hi,
func collectionView(_ collectionView: UICollectionView, editActionsForItemAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? called and return action, but nothing happens.  

swipeActionView not moving

everything worked fine in ios 12.4

Im use SwipeCellKit with iGListKit

**Comment by kurabi** [comment]
Please see #333
