### ISSUE TITLE
Animating CollectionViewCell triggers prepareForReuse and causes buggy behavior.

### ISSUE THREAD

**Issue by Harout360** [SwipeCellKit/SwipeCellKit#350]
Steps to reproduce issue:
1. Have multiple cells of single type
2. Animate cell on isHighlighted
3. Quickly after animation, start swipe to delete on cell
4. Cell gets reset to center while in the middle of an incomplete swipe

One workaround I thought might work is preventing **prepareForReuse** when the state is not .center, but this leads to the issue of the swiped cell getting dequedForReuse before being reset to center.

**Comment by kurabi** [comment]
I don't understand step 3 to 4.

> ... start swipe to delete on cell
> Cell gets reset to center while in the middle of an incomplete swipe

Why would the cell delete during swipe?

**Comment by Harout360** [comment]
Sorry my misunderstanding, thanks for your work
