### ISSUE TITLE
SkeletonView + SwipeCellKit Compatibility Issue... Swipe Actions Overlay Each Other when both are in effect

### ISSUE THREAD

**Issue by mechmatt01** [SwipeCellKit/SwipeCellKit#352]
Hello! First off, I would like to say thank you for your fantastic work. More recently, I have encountered this issue, and I can't seem to figure it out. I am using a tableView and when I swipe on it the actions that looked normal for about the last six months have just started overlaying each other, and I can't seem to figure out why. As you can see in the video, there are two more actions behind that one, but it seems as if they are all confined to that first and foremost action. This occurs on iOS 13 as well as 12. I am using Xcode 10.3. I found out that this is caused by another pod named ["SkeletonView"](https://github.com/Juanpe/SkeletonView). I am not sure why this is though.

[Video](https://www.dropbox.com/s/k5ka0clidlxaw0z/CellsVideo.MP4?dl=0)

**Comment by kurabi** [comment]
You need to compare the view hierarchy between a project that does use SkeletonView vs one that does not. SkeletonView must be doing something that is impacting the SwipeCellKit. SkeletonView is a huge project that is too large for me to dig into.

**Comment by darshit261991** [comment]
Even I am facing the same issue. Second swipe action gets overlay on the first one. Did anyone find the solution for this issue?

**Comment by kurabi** [comment]
> Even I am facing the same issue. Second swipe action gets overlay on the first one. Did anyone find the solution for this issue?

Are you also using SkeletonView?

**Comment by darshit261991** [comment]
Yes

**Comment by mechmatt01** [comment]
It seems that the Skeleton View is causing this issue I would try downgrading that

**Comment by darshit261991** [comment]
Can you please provide which version to use so I don't encounter problem of Skeleton View?

**Comment by darshit261991** [comment]
Currently I am using Version - 2.6.0

**Comment by mechmatt01** [comment]
@darshit261991 1.7.0 seems to work fine for me. I am not sure where 2.6.0 is from but the latest version at least when using pods currently I think is 1.8.1. Using 1.7.0 should solve your issues. Let me know if it does or does not.

**Comment by virusnik** [comment]
> @darshit261991 1.7.0 seems to work fine for me. I am not sure where 2.6.0 is from but the latest version at least when using pods currently I think is 1.8.1. Using 1.7.0 should solve your issues. Let me know if it does or does not.

Oh thanks, I lost a lot of time, before I was read decisions this issue here

**Comment by kurabi** [comment]
Closing issue as this seems like Skeleton View issue.
