### ISSUE TITLE
Minimum deployment target

### ISSUE THREAD

**Issue by wolfey** [SwipeCellKit/SwipeCellKit#40]
What is the minimum ios version supported? I cloned the repo and was able to build for ios 8. However, when I try to import it into my project (with ios target 8.0), I get the following error:

```
[!] Unable to satisfy the following requirements:

- `SwipeCellKit` required by `Podfile`

Specs satisfying the `SwipeCellKit` dependency were found, but they required a higher minimum deployment target.
```

**Comment by kazzar** [comment]
same issue here, the requirements are clear:

> iOS 9.0+

but i changed in my pod file:
`platform :ios, '9.0' ` to `platform :ios, '10.0'` and now it works

**Comment by kurabi** [comment]
Fixed. Will be part of upcoming tag.
https://github.com/SwipeCellKit/SwipeCellKit/commit/b2b571de53b7854827371fc991801bd5c761b7f9
