### ISSUE TITLE
Adding @objc annotations to framework classes

### ISSUE THREAD

**Issue by wolfey** [SwipeCellKit/SwipeCellKit#41]
In order to use Swift classes in Objective-C code, they need to be annotated with `@objc`. Would it be possible to add these annotations?

**Comment by kurabi** [comment]
Going to think about this. Its not easy as putting @objc on public classes/protocols.

**Comment by kurabi** [comment]
@wolfey This library was built with only Swift in mind, its not as easy as adding @objc to classes, structs and extensions would need to be modified to support Objective-c correctly. I am willing to consider pull requests if someone can convince me it is easy to add.

**Comment by wolfey** [comment]
@kurabi thanks for looking into it! I was able to port my views to swift and now it works like a charm :)
