### ISSUE TITLE
UI Bug(Tableview with multiple custom cells)

### ISSUE THREAD

**Issue by mericksters** [SwipeCellKit/SwipeCellKit#43]
Hi, I think I may have found a bug or I don't know,

here's what happened, I created a tableview with 2 custom cells, one being a subclass of SwipeTableViewCell and the other one, just an empty cell.

Whenever the other non SwipeTableViewCell is not being dequeued, it seems that the hideSwipe is not being called when swiping another cell which leaves the other cell on swipe state even when you swipe another cell.

Workaround I did is subclassing both custom cells as SwipeTableViewCell, which gives me the behavior I want upon doing this.

if there's something I missed as part of cell's configuration to get what I want please let me know.

Please see screenshot below:

<img width="374" alt="screen shot 2017-05-27 at 2 03 39 pm" src="https://cloud.githubusercontent.com/assets/8444507/26518612/2c3e6c12-42e6-11e7-97e0-6cffdb6566bf.png">

**Comment by kurabi** [comment]
Can you please post a sample project with this issue? Thanks.

**Comment by kurabi** [comment]
Fixed by issue #37, with commit 73ff931fb2cf543b5511648f437e9a79ec4b4ae5
