### ISSUE TITLE
setSwipeOffset and the delegate

### ISSUE THREAD

**Issue by nameghino** [SwipeCellKit/SwipeCellKit#49]
Is there any way of not triggering the willStart/didEnd delegate callbacks when using setSwipeOffset? I need to tell if the user initiated the swipe or it's the programmatic setSwipeOffset(). Any pointers to doing this?

**Comment by kurabi** [comment]
Create a property that you set to `true` when you set the swipe offset. Then check if that property is true/false on the delegate.
