### ISSUE TITLE
swift 4 compile errors

### ISSUE THREAD

**Issue by n0an** [SwipeCellKit/SwipeCellKit#54]
There're issues with this library when run in Xcode 9 with Swift 4. Some of issues I could fix by myself, but there're issues I can't fix:
`etSwipeOffset(.greatestFiniteMagnitude * orientation.scale.negated()`

and here:
`let maxOffset = min(bounds.width, abs(offset)) * orientation.scale.negated()`

Xcode complains:
`'negated()' is unavailable: Please use operators instead. 'negated()' was obsoleted in Swift 4`

Do you have idea how to fix this issue?

**Comment by kurabi** [comment]
I have yet to to test this project with iOS 11 or Swift 4.`negated()` is the equivalent of multiplying by `-1`.

**Comment by kurabi** [comment]
There is a branch now that is dedicated to Swift4/iOS 11 changes. 45dd5086d903c53ecfc317d587ae444746f28f4b
