### ISSUE TITLE
Using SwipeCellKit in UITableView inside UIScrollView

### ISSUE THREAD

**Issue by seidju** [SwipeCellKit/SwipeCellKit#55]
Hi!
I have an `UIScrollView`, which contains multiple `UITableViewController`, so could horizontally swipe between them. But when I add `SwipeTableViewCell's` in `tableView` and if i would try to swipe left/right i can only access `SwipeActions`, but not the `UIScrollView`...
Is it possible to set some kind of area on `SwipeTableViewCell` (for example, from left corner to centre of the cell) where if i swipe, i would see `SwipeActions`, and if i swipe outside this area -> then just use simple paging functionality between controllers?
Thanks!

**Comment by kurabi** [comment]
Its not. Without `SwipeTableViewCell`, do the editActions on UITableView work in your case?

**Comment by seidju** [comment]
You mean set `scrollView.panGestureRegognizer.delegate = self` ? Because in this case it fails with error: `UIScrollView's built-in pan gesture recognizer must have its scroll view as its delegate.` Or I need to add another `panGestureRecognizer` to `scrollView`?

**Comment by kurabi** [comment]
Yes, you need to put a `panGestureRecognizer` and then use the `shouldRecognizeSimultaneouslyWith` to disable cell's panGestureRecognizer when when you choose its appropriate.

**Comment by kurabi** [comment]
Going to close this issue as supporting edge swipe only does not make sense from a UX perspective and conflicts with the back gesture. You should be able to accomplish what you need with the above mentioned suggestion.

**Comment by appdevsben** [comment]
Hiii seidju, 
Can you please add the code here for solution?
