### ISSUE TITLE
How to disable drag multiple rows from table?

### ISSUE THREAD

**Issue by j0sem4rio** [SwipeCellKit/SwipeCellKit#57]
The user can select two cell, how disable this feature

**Comment by kurabi** [comment]
This is a known issue. Its not trivial to fix and is something that we are considering to fix in v2.0

**Comment by theraad** [comment]
This is still an issue and is not easily solved. With normal tableviews you can simply disable multiple touch on the tableview and the native swiping becomes limited to one at a time, but if you do the same with cells that have implemented SwipeCellKit, the issue still exists even after disabling multiple touch. 

Just pointing this out cause i don't think the issue should've been closed at the time.

**Comment by kurabi** [comment]
It was always stated that this is a known issue that is not easily solved. I will reopen it as I do think there is a solution now.

**Comment by ArmyXomuiL** [comment]
Please fix this... :-(

**Comment by kurabi** [comment]
Fix for this is on `develop` branch.
