### ISSUE TITLE
Selected state is lost

### ISSUE THREAD

**Issue by MattNewberry** [SwipeCellKit/SwipeCellKit#58]
In `showActionsView` (https://github.com/SwipeCellKit/SwipeCellKit/blob/develop/Source/SwipeTableViewCell.swift#L218), the current selected cells are force deselected. What's the reason behind this? I'd like to keep the selected state of a cell, and it's unclear why the swipe gesture needs to impact this state.

**Comment by MattNewberry** [comment]
I've been able to resolve this, and will submit a PR soon: https://github.com/MattNewberry/SwipeCellKit/commit/07917de65b37e858e8b2b33fbfe24bdf75beeaab

**Comment by kurabi** [comment]
Some reasons to why this is the case:
1. That is the default behavior of he current swipe actions on UITableView.
2. The cell selection and swipe can momentarily overlap if you touch long enough then begin to drag to reveal swipe actions, this means users might see the cell selected, and on other swipes, it may not. That doesn't seem like a great experience.
3. One way to cancel the swipe actions is to click outside those actions, sush as the cell.

This avoids being in 2 states at once and is more consistent to the user irregardless of how hard their initial touch may have been.

**Comment by kurabi** [comment]
Fixed and will be part of next release.
