### ISSUE TITLE
Play nice with iOS 11

### ISSUE THREAD

**Issue by tfsjohan** [SwipeCellKit/SwipeCellKit#60]
It would be nice if SwipeCellKit could work together with the similar system in iOS 11. I would like to use SwipeCellKit as a fallback for earlier versions of iOS, but right now that does not work since cells get unresponsive when a cell inherit from SwipeCellKit's UITableViewCell's subclass.

**Comment by kostapappas** [comment]
Same problem here in iOS 11  after the first touch the tableview don't respond to any tap.

**Comment by kostapappas** [comment]
duplicate, look on previous open issues. 
add the following manually in pod  file in setGestureEnabled function
if #available(iOS 11, *) {
            // Workaround for iOS 11+, do nothing
        } else {
            gestureRecognizers?.forEach {
                guard $0 != panGestureRecognizer else { return }
                
                $0.isEnabled = enabled
            }
        }
