### ISSUE TITLE
Can be used with any CustomTableViewCell?

### ISSUE THREAD

**Issue by n4nachiket** [SwipeCellKit/SwipeCellKit#64]
Can I use this with custom cell that I've made or I must use SwipeTableViewCell?

**Comment by n4nachiket** [comment]
So stupid of me. I only had to inherit the SwipeCell

**Comment by aliihsanural** [comment]
Can you explain to work with Custom Cell please ?. I dont find any solution.

**Comment by n4nachiket** [comment]
Inherit your custom cell from swipecell and it should work.

Regards,
Nachiket Hole

On 30-Mar-2018, at 2:05 PM, Ali Ihsan URAL <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you explain to work with Custom Cell please ?. I dont find any solution.
