### ISSUE TITLE
Allow Multiline Labels

### ISSUE THREAD

**Issue by DaveBatton** [SwipeCellKit/SwipeCellKit#66]
The built-in swipe action allows me to use multi-line labels such as "Mark as\nComplete". I'd love to see this capability in SwipeCellKit.

**Comment by snod** [comment]
The labels already allow multiline text, however I can't seem to get them aligned properly with the icons when using a mixture of single/multiline texts.

Using `buttonVerticalAlignment` or `center` in `SwipeTableOptions` doesn't make any difference.

**Comment by kurabi** [comment]
@DaveBatton As @snod mentioned, you can add line breaks. Regarding alignment, that is a bug as the should be the default behavior. I'll take a look. In the mean time, the quick (albeit non-ideal) is to add a trailing line break if you want all labels to align.

**Comment by Datastore24Kirill** [comment]
Icon and Label not in center vetical. 
iOS 12
![image](https://user-images.githubusercontent.com/13977544/70134479-3b5d5080-1699-11ea-85d9-a7f9ad8f72f7.png)
