### ISSUE TITLE
Action button background color does not work with UIColor.clear

### ISSUE THREAD

**Issue by JorgeAGomez** [SwipeCellKit/SwipeCellKit#67]
Hello (Using Xcode 8.3.2 and Swift 3)

I am using three action buttons with UIImages in my cell. Two buttons on the right side and one on the left side. I have been trying to remove the backgroundColor using UIColor.clear but it still returns a grey background. I tested the actionButton.backgroundColor = UIColor.red and it works as expected. However when I try actionButton.backgroundColor = UIColor.clear the background is grey. 

Maybe I am missing a step or doing something wrong? Any comments or suggestions on how to remove that grey background?

Here are some screenshots for reference: 

(makeActive and makeInactive are action buttons)

makeActive.backgroundColor = UIColor.clear
makeInactive.backgroundColor = UIColor.clear

![img_0032](https://user-images.githubusercontent.com/6026875/28728295-50e952fa-7385-11e7-9d54-f2799f72d5cb.PNG)

makeActive.backgroundColor = UIColor.red
makeInactive.backgroundColor = UIColor.blue

![img_0031](https://user-images.githubusercontent.com/6026875/28728342-88d838fc-7385-11e7-8c63-8f3febd0f8d1.PNG)

**Comment by mad102190** [comment]
Are you sure the gray isn't the tableview's background color?

**Comment by JorgeAGomez** [comment]
@mad102190  tableView's background and cell's background is set to Clear. The background you see is an image I have set up behind the tableView.

**Comment by kurabi** [comment]
@JorgeAGomez Can you post or look at the debug view hiarchy to see which view is gray?

**Comment by JorgeAGomez** [comment]
Hello @kurabi . Here are two pictures of the debug view hierarchy. Any suggestions?? Thanks!!

![screen shot 2017-08-14 at 7 07 18 pm](https://user-images.githubusercontent.com/6026875/29298279-dde5258e-8123-11e7-8fc5-8550c1344324.png)
![screen shot 2017-08-14 at 7 07 28 pm](https://user-images.githubusercontent.com/6026875/29298280-dde843b8-8123-11e7-9d1f-dcecb815717a.png)

**Comment by kurabi** [comment]
@JorgeAGomez Please set the `SwipeTableOptions` `backgroundColor` property to the color you would like.

**Comment by JorgeAGomez** [comment]
@kurabi Awesome! That worked. :) Thank you very much!

**Comment by Skornos** [comment]
@kurabi awesome library, appreciate it 🤟

But it's important to mention that if you are setting the color to `.clear` then you need to do it not just within `editActionsOptionsForRowAt` but also within `editActionsForRowAt`.

The bug is caused by this code in `SwipeActionButtonWrapperView`:

```
    func configureBackgroundColor(with action: SwipeAction) {
        guard action.hasBackgroundColor else {
            isOpaque = false
            return
        }
        
        if let backgroundColor = action.backgroundColor {
            actionBackgroundColor = backgroundColor
        } else {
            switch action.style {
            case .destructive:
                actionBackgroundColor = #colorLiteral(red: 1, green: 0.2352941176, blue: 0.1882352941, alpha: 1)
            default:
                actionBackgroundColor = #colorLiteral(red: 0.862745098, green: 0.862745098, blue: 0.862745098, alpha: 1)
            }
        }
    }

```

**Comment by BuddyLReno** [comment]
@kurabi new to ios development.  I'm not sure where/how to set the table options.  There's a return function for SwipeOptions giving me a spot to set those, but not for table options.

**Comment by BuddyLReno** [comment]
Ah! I finally understand it! Just needed to walk away for a little bit and redigest @Skornos's comment.
