### ISSUE TITLE
Action views sometimes invisible 

### ISSUE THREAD

**Issue by firvorski** [SwipeCellKit/SwipeCellKit#70]
On some table cells (seemingly) randomly action views are not visible. They still perform their actions correctly when swiped, however, any titles, icons and colours are not visible. 

I cannot figure out what it depends on but it happens quite often, almost once every session. It rarely affects all cells, instead, for example, 3 cells out of 8 would be affected.

The configuration is:
* Actions on both sides (and this affects both of them)
* Button style: background colour, 
* Button display mode: title and image
* Expansion style: .fill (one side could alternatively also be .selection, but that doesn't make any difference)

Left side OK:
![left_ok](https://user-images.githubusercontent.com/5808204/29036344-fc8362ae-7b96-11e7-8065-e262b55f5b79.jpg)
Left side invisible:
![left_not_ok](https://user-images.githubusercontent.com/5808204/29036343-fc81f770-7b96-11e7-8175-07862b805808.jpg)

Right side OK:
![right_ok](https://user-images.githubusercontent.com/5808204/29036342-fc81bc24-7b96-11e7-83b1-581e656c938a.jpg)

Right side invisible:
![right_not_ok](https://user-images.githubusercontent.com/5808204/29036341-fc81b7b0-7b96-11e7-80e1-961a664b8927.jpg)

**Comment by kurabi** [comment]
Look at the the debug view hierarchy. It seems like your view customization is covering up the buttons. Can't really help without a sample project or more detail.

**Comment by denirorobert** [comment]
Have you found a root cause and how to fix it?

**Comment by firvorski** [comment]
No, I wasn't able to, so I switched to a different repository.
