### ISSUE TITLE
How to change SwipeAction image on tap?

### ISSUE THREAD

**Issue by szooky** [SwipeCellKit/SwipeCellKit#73]
I would like to change `SwipeAction` image after tap. I tried like this, however it's not working.

        let likeAction = SwipeAction(style: .default, title: nil) { action, indexPath in
            let note = self.getNote(for: indexPath)
            
            if note.isLiked {
                NotesRepository.unlike(note)
                action.image = UIImage(named: "icon-heart-off")
            } else {
                NotesRepository.like(note)
                action.image = UIImage(named: "icon-heart")
            }
        }

Is it a bug or intended behaviour? Is there a way to achieve changing this image on tap?

**Comment by kurabi** [comment]
Can you look at the "Mark Read" and "Mark Unread" example in the MailExample app. The icon and text changes there.

**Comment by szooky** [comment]
Thank you for your answer, however it's not what I want to achieve. In "Mark Read/Unread" .hidesWhenSelected and .selection expansion style is used. After tap buttons hides automatically and icon changes when it's not visible on screen (if you set hidesWhenSelected = false for this cell you will see that after tap "Mark Read" remains the same and only blue indicator in cell animates). I would like to use expansion style .none and .hidesWhenSelected = false, user swipe on cell to see options, click on a button and button icon changes but buttons still remain visible on screen.

**Comment by kurabi** [comment]
@szooky I am assuming the highlightImage on the action is not enough. With that said, add a `SwipeActionTransitioning` transitionDelegate on the action you are interested in. `SwipeActionTransitioningContext` will give you access to the action button where you can manipulate it.
