### ISSUE TITLE
How can I set .imageOnly for delete action?

### ISSUE THREAD

**Issue by umekun123** [SwipeCellKit/SwipeCellKit#74]
I am using this code, but I still cannot find how I can set .imageOnly for this deleteAction.
I thought I can use the default trash icon image from this library, but I should set my own image by myself?

func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]? {
    guard orientation == .right else { return nil }

    let deleteAction = SwipeAction(style: .destructive, title: "Delete") { action, indexPath in
        // handle action by updating model with deletion
    }

    // customize the action appearance
    deleteAction.image = UIImage(named: "delete")

    return [deleteAction]
}

**Comment by VasuNIPL** [comment]
hi

**Comment by VasuNIPL** [comment]
i wan't to access in my tableview custom cell it this possible or not?

**Comment by kurabi** [comment]
@umekun123 The library does not contain images. It is only in the sample app that images are used. So please use your own images if you would like to show images for the buttons.

**Comment by umekun123** [comment]
Thanks, that explains all.
