### ISSUE TITLE
SwipeActionView is clipped

### ISSUE THREAD

**Issue by MattNewberry** [SwipeCellKit/SwipeCellKit#75]
I've run across a difficult, and seemingly unpredictable bug... 

In rare cases, the action view will be completely hidden from view. In using the visual debugger in Xcode, and turning on "Clipped Views", the view then appears. I've checked all the superviews for `clipsToBounds` to ensure it's turned off, and as you can see, the constraints are properly set given it's positioned correctly. 

The only lead I have is that it more commonly fails to display when a cell appears in a new section for the first time. In other words, if we have two sections, then insert a third with a new cell in that section, the new cell appearing in the new section is more frequently where I'll see this behavior.

Has anyone run into this before? 

(Clipped view on the left, actual displayed result on the right)
<img width="686" alt="clippedviews" src="https://user-images.githubusercontent.com/108004/29521848-26ac8358-8655-11e7-9d8f-726123e8f074.png">

**Comment by kurabi** [comment]
@MattNewberry Stange. So u where not able to determine which view had `clipsToBounds` set to true? Are you using auto resizing cells in the `UITableView` with a height of automatic?

**Comment by MattNewberry** [comment]
@kurabi I went up the entire stack and ensured every superview had `clipsToBounds` set to false to be overly sure, and still no change. In this case we're using a predetermined cell height. The custom cell subclass does have "auto resizes subviews" on.

**Comment by kurabi** [comment]
@MattNewberry Did you look at the 3D view of the hierarchy to identify the view that was blocking the actions button from being seen? Also is this on simulator or a device? Thanks

**Comment by MattNewberry** [comment]
@kurabi That's whats most confusing... there doesn't appear to be a view on top of the actions clearly clipping it. When I 3D view it, there's no smoking gun. When I click on the area where the actions should be displayed, the selected view becomes the table view behind it.

**Comment by kurabi** [comment]
@MattNewberry hmmm, just to confirm, the action buttons always appear in the debug view hierarchy regardless if "Clipped Views" button is turned on or off?

**Comment by MattNewberry** [comment]
@kurabi They're always in the hierarchy, however they only appear when `Clipped Views` is enabled in the visual debugger.

**Comment by MattNewberry** [comment]
What's odd as well is that the button contents seemingly is at a lower Z index than the rest of the action view. 

("Arrived" text is in the background)
<img width="585" alt="screen shot 2017-08-21 at 2 06 17 pm" src="https://user-images.githubusercontent.com/108004/29532204-f0c31f02-8679-11e7-9558-2fa982ac8f76.png">

**Comment by MattNewberry** [comment]
This appears to be an internal issue rather than one related to SwipeCellKit... going back 6 months to our initial integration, I'm unable to reproduce. I'll report back when I'm able to track it down to help anyone else who may have this issue in the future.

**Comment by MattNewberry** [comment]
For anyone who may find this down the road... Inexplicably, this issue was introduced when triggering a sort of our list from a `NSFetchedResultsControllerDelegate` method, in which the sorting method then persisted new properties that also triggered the same delegate callback. While I believe the issue lies within an internal oddity of our app, the issue has seemingly gone away by breaking out separate `fetchedResultsControllers` for our purposes.
