### ISSUE TITLE
Crash appears when section is deleted

### ISSUE THREAD

**Issue by denirorobert** [SwipeCellKit/SwipeCellKit#76]
When I delete sections from tableview I got crash in function:
`func performFillAction(action: SwipeAction, fillOption: SwipeExpansionStyle.FillOptions)`

line 452 in called: `tableView.deleteRows(at: [indexPath], with: .none)`

I think that the root case is in fact that at that moment in my code I am deleting section with `tableView.deleteSections(indexSet, with: .fade)`, I've tried the same steps without SwipeCellKit and everything work fine.

Error message:

> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (1) must be equal to the number of rows contained in that section before the update (1), plus or minus the number of rows inserted or deleted from that section (0 inserted, 1 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).'

**Comment by denirorobert** [comment]
not a bug: solution is to use action.fulfill(with: .delete) instead

**Comment by evtaccount** [comment]
instead what?
