### ISSUE TITLE
Expandable Cells

### ISSUE THREAD

**Issue by amiinous** [SwipeCellKit/SwipeCellKit#78]
Hi
Thank you for your great work!

I have expandable tableViewCells by implementing the `heightForRowAt ` tableview delegate method (I point out the implementation approach cause there many ways to implement the expansion). However, the expansion content (which at their normal state should be invisible) is visible (but the buttons in this area are not interactive until the expansion really occurs, i.e. the border between cell gets expanded).

How can I fix this?

Thanks,

**Comment by kurabi** [comment]
I don't understand your issue. Please post screenshots.
