### ISSUE TITLE
Read and Unread Cell marker override 

### ISSUE THREAD

**Issue by smkdoss73** [SwipeCellKit/SwipeCellKit#79]
Hi Team, 

SwipeCellKit libraries is very interesting. I used SwipeCellKit libraries source code  in my existing projects. 
I feel something better  please check my attachment.

![unreadmail](https://user-images.githubusercontent.com/7939817/30024689-932a68cc-9192-11e7-98a4-7f6e77057d63.gif)

**Comment by kurabi** [comment]
Thanks. This sample app is to just demo the features, the new entry indicator isn't one of those.
