### ISSUE TITLE
Image alignment

### ISSUE THREAD

**Issue by sarathsarah** [SwipeCellKit/SwipeCellKit#80]
My tableView cell row height is 44 and I'm using 2x and 3x image means The image is not placed well. Its got streched more.

(Im using images of 96x96(fb), 128x128(flower) dimension) 
![screen shot 2017-09-11 at 5 31 23 pm](https://user-images.githubusercontent.com/10936106/30273561-1fb1b8b6-9717-11e7-97fa-9fe70cf3bcc3.png)

If cell get expand.

![screen shot 2017-09-11 at 5 36 59 pm](https://user-images.githubusercontent.com/10936106/30273745-f52fa052-9717-11e7-9c75-3531a2d56134.png)

**Comment by kurabi** [comment]
Images are not stretched or shrunk. Please use correct size images.
