### ISSUE TITLE
SwipeActions not visible for dequeued rows

### ISSUE THREAD

**Issue by softwarejoint** [SwipeCellKit/SwipeCellKit#85]
Swipe actions are not visible for dequeued rows. Issue is when uitableview creates rows that are not visible when they are created and then get dequeued for reuse, the actions are not visible.

I fixed it in my personal code, as I have not forked the repo, I am sending the fix here in comment.

file: SwipeTableViewCell.swift
call hierarchy 
```
   prepareForReuse
   reset
```

function updated: 
```
  reset
```

final code function
```
  func reset() {
         state = .center
+        clipsToBounds = false   //line added
         actionsView?.removeFromSuperview()
         actionsView = nil
     }

```

**Comment by kurabi** [comment]
Hi @softwarejoint. Can you describe how you are initializing your table view cell?

The `configure()` in `SwipeTableViewCell.swift` method currently sets `clipsToBounds = false`. So I am trying to understand where that is getting reset or possible never called.

Thanks
