### ISSUE TITLE
Swipe doesn't work when tableview is in editing mode

### ISSUE THREAD

**Issue by armendh** [SwipeCellKit/SwipeCellKit#89]
On line 118 in SwipeTableViewCell.swift we got:
guard isEditing == false else { return }

so commenting this line works for now. 

Maybe add an option for the dev if he wants to enable swipe in editing mode?

**Comment by kurabi** [comment]
Thats the default behavior of how swipe actions work within iOS. Supporting this mode is non-trivial.

**Comment by rolandleth** [comment]
I was going to open the same issue, with the same suggestion, albeit more detailed :( 

May I ask why it's non-trivial? Don't have as much experience related to this as you, obviously, so it's a genuine question. Maybe we can find a way?

If there really is no easy way, would you consider giving this option to the developer, and explain they do this at their own risk? I have _very briefly_ tried it on the demo app, and for very simple use cases like "use edit more just for reorder", it seems to work okay.

Thank you!

**Comment by BeauNouvelle** [comment]
Anyone got a work around for this now?
