### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by matin-kaj** [SwipeCellKit/SwipeCellKit#90]
Any plans to update the library to support Swift 4?

**Comment by kurabi** [comment]
Please look at swift 4 branch.

**Comment by ripventura** [comment]
I have my own pods which use SwipeCellKit as dependency, and since you can't ":branch" on the .podspec file, theres no way to access the swift 4 branch...
Is there an ETA to merge this branch into master?

**Comment by kurabi** [comment]
In the next few days.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
