### ISSUE TITLE
negated() is unavailable

### ISSUE THREAD

**Issue by ibrahimtall** [SwipeCellKit/SwipeCellKit#91]
Just updated to xcode 9.0 I am getting an error **"negated() is unavailable: please use operators instead"** in SwipeTableViewCell+Display.swift I have looked around and there does not seem to be anything about this anywhere.

**Comment by ibrahimtall** [comment]
I guess multiplying by -1 fixes that. Sorry

**Comment by kurabi** [comment]
Please upgrade to the latest version of SwipeCellKit
