### ISSUE TITLE
iOS 11 swipCell issue.

### ISSUE THREAD

**Issue by Ilesh** [SwipeCellKit/SwipeCellKit#92]
Hello, Developer. Hope you are doing great. I face one issue when I update my device iOS 11 and run build in debug mode. Swipe right is working only first time. When I hide again I can't open it again in swipe to right in any cell. I am deque my cell. I tried #85 solution but it's not working for me. Thanks in Advance. @kurabi, @sgruby, @jerkoch, @sammygutierrez, @mbutan

**Comment by hazemmaher92** [comment]
same issue here , and the UITableView became unresponsive to taps

**Comment by ysmanse** [comment]
I've same issue, anybody got the solutions?

**Comment by sgruby** [comment]
I haven’t seen this issue in the Simulator. Have you been able to reproduce it in the SImulator or just a device? Do you have a sample app that exhibits the behavior? Since I’ve updated all my projects, I want to make sure this isn’t going to cause me a problem. Thanks!

**Comment by Ilesh** [comment]
Hello, @sgruby, I face this issue in Device(I Tasted in iPhone 5S and Xcode 8.3.1). Thanks for your reply. Is this the right way?

**Comment by aloveric** [comment]
+1, same issue

**Comment by mduplifting** [comment]
+1, same behaviour

**Comment by honcharenko13** [comment]
+1, same behaviour

**Comment by dustinrwh** [comment]
Same issue here

**Comment by artemtkachenko** [comment]
+1, same issue, using 1.9.0 version

**Comment by sgruby** [comment]
If you look at the [change log](https://github.com/SwipeCellKit/SwipeCellKit/blob/develop/CHANGELOG.md), the author notes:
>>>Fix issue related to iOS 11. SwipeCellKit was inadvertently enabling/disabling various gestures on UITableView, including system level ones in hopes of disabling 3D Touch on swiped UITableViewCells. Developers must now handle the disabling/enabling of 3D touch when cell is swiped with the aid of SwipeTableViewCellDelegate. (#48)

Furthermore, there is a [release](https://github.com/SwipeCellKit/SwipeCellKit/releases/tag/1.9.1) for this version.

I just re-verified that the behavior happens under 1.9.0, but not the current 1.9.1. Has anyone seen this issue with 1.9.1?

**Comment by dustinrwh** [comment]
Thanks @artemtkachenko 

Using 1.9.1 (via master) solved the issue for me!

If you are using CocoaPods, just use master by doing the following in your Podfile:
 
`pod 'SwipeCellKit', :git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'master'`

Then run the following command in Terminal: 

`pod install`

Thanks for all the hard work on this awesome framework!

**Comment by rr-dw** [comment]
Also had same issue. I can also verify that 1.9.1 fixed it.

**Comment by Blackening999** [comment]
Close issue please
