### ISSUE TITLE
Trying to show actions programmatically

### ISSUE THREAD

**Issue by claucgmz** [SwipeCellKit/SwipeCellKit#95]
I am trying to trigger swipe and show actions programmatically with cell.showSwipe(orientation: .right, animated: true, completion: nil) but nothing happens :/

**Comment by rahulmeena13** [comment]
+1 same here, not working

**Comment by kurabi** [comment]
This works fine in the sample add. I added this in the `viewDidLoad` method in the sample app and it worked just fine.
`DispatchQueue.main.asyncAfter(deadline: .now() + 2.0) {
            let cell = self.tableView.cellForRow(at: IndexPath(row: 0, section: 0)) as! SwipeTableViewCell
            cell.showSwipe(orientation: .right, animated: true, completion: nil)
        }`

**Comment by AhmedFitoh** [comment]
it's working , try to change your orientation  direction
