### ISSUE TITLE
showActionsView on Header and Footer cell

### ISSUE THREAD

**Issue by shinrikiken** [SwipeCellKit/SwipeCellKit#98]
How can I able this swiped  action on header cell and footer cell?, because I have seen this method `func showActionsView(for orientation: SwipeActionsOrientation) -> Bool`
Inside this method, it allows only cell that has its `indexPath`

I try to figure it out, There is one way to achieve this requirement is that, I have to display Header and Footer as a regular cell from 
`func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell` this method

which I have to know exactly how to define Header and Footer indexPath, this is a bit tricky, and it is inflexible, That is why I have come to ask for your help. 

Thanks in advance

**Comment by kurabi** [comment]
If you have headers/footers that need swipe actions, then make them a `UITableViewCell`.
